version: '3.8'

services:
  proxy-node:
    build:
      context: .
      dockerfile: node/Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      - PS_MASTER_KEY=${PS_MASTER_KEY:-my-secret-key}
      - GRPC_LISTEN=:9090
    volumes:
      - ./data:/data
