// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: registry.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryManagementService_ListServices_FullMethodName  = "/proxyswarm.RegistryManagementService/ListServices"
	RegistryManagementService_UpsertService_FullMethodName = "/proxyswarm.RegistryManagementService/UpsertService"
	RegistryManagementService_DeleteService_FullMethodName = "/proxyswarm.RegistryManagementService/DeleteService"
)

// RegistryManagementServiceClient is the client API for RegistryManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryManagementServiceClient interface {
	ListServices(ctx context.Context, in *RegistryListServicesRequest, opts ...grpc.CallOption) (*RegistryListServicesResponse, error)
	UpsertService(ctx context.Context, in *RegistryUpsertServiceRequest, opts ...grpc.CallOption) (*RegistryUpsertServiceResponse, error)
	DeleteService(ctx context.Context, in *RegistryDeleteServiceRequest, opts ...grpc.CallOption) (*RegistryDeleteServiceResponse, error)
}

type registryManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryManagementServiceClient(cc grpc.ClientConnInterface) RegistryManagementServiceClient {
	return &registryManagementServiceClient{cc}
}

func (c *registryManagementServiceClient) ListServices(ctx context.Context, in *RegistryListServicesRequest, opts ...grpc.CallOption) (*RegistryListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryListServicesResponse)
	err := c.cc.Invoke(ctx, RegistryManagementService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryManagementServiceClient) UpsertService(ctx context.Context, in *RegistryUpsertServiceRequest, opts ...grpc.CallOption) (*RegistryUpsertServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpsertServiceResponse)
	err := c.cc.Invoke(ctx, RegistryManagementService_UpsertService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryManagementServiceClient) DeleteService(ctx context.Context, in *RegistryDeleteServiceRequest, opts ...grpc.CallOption) (*RegistryDeleteServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryDeleteServiceResponse)
	err := c.cc.Invoke(ctx, RegistryManagementService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryManagementServiceServer is the server API for RegistryManagementService service.
// All implementations must embed UnimplementedRegistryManagementServiceServer
// for forward compatibility.
type RegistryManagementServiceServer interface {
	ListServices(context.Context, *RegistryListServicesRequest) (*RegistryListServicesResponse, error)
	UpsertService(context.Context, *RegistryUpsertServiceRequest) (*RegistryUpsertServiceResponse, error)
	DeleteService(context.Context, *RegistryDeleteServiceRequest) (*RegistryDeleteServiceResponse, error)
	mustEmbedUnimplementedRegistryManagementServiceServer()
}

// UnimplementedRegistryManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryManagementServiceServer struct{}

func (UnimplementedRegistryManagementServiceServer) ListServices(context.Context, *RegistryListServicesRequest) (*RegistryListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedRegistryManagementServiceServer) UpsertService(context.Context, *RegistryUpsertServiceRequest) (*RegistryUpsertServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertService not implemented")
}
func (UnimplementedRegistryManagementServiceServer) DeleteService(context.Context, *RegistryDeleteServiceRequest) (*RegistryDeleteServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedRegistryManagementServiceServer) mustEmbedUnimplementedRegistryManagementServiceServer() {
}
func (UnimplementedRegistryManagementServiceServer) testEmbeddedByValue() {}

// UnsafeRegistryManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryManagementServiceServer will
// result in compilation errors.
type UnsafeRegistryManagementServiceServer interface {
	mustEmbedUnimplementedRegistryManagementServiceServer()
}

func RegisterRegistryManagementServiceServer(s grpc.ServiceRegistrar, srv RegistryManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryManagementService_ServiceDesc, srv)
}

func _RegistryManagementService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryManagementServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryManagementService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryManagementServiceServer).ListServices(ctx, req.(*RegistryListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryManagementService_UpsertService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryUpsertServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryManagementServiceServer).UpsertService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryManagementService_UpsertService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryManagementServiceServer).UpsertService(ctx, req.(*RegistryUpsertServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryManagementService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryDeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryManagementServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryManagementService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryManagementServiceServer).DeleteService(ctx, req.(*RegistryDeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryManagementService_ServiceDesc is the grpc.ServiceDesc for RegistryManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxyswarm.RegistryManagementService",
	HandlerType: (*RegistryManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _RegistryManagementService_ListServices_Handler,
		},
		{
			MethodName: "UpsertService",
			Handler:    _RegistryManagementService_UpsertService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _RegistryManagementService_DeleteService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
