// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: registry/registry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryServiceConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Accounts      []*Account              `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	TemplateLinks []*RegistryTemplateLink `protobuf:"bytes,2,rep,name=template_links,json=templateLinks,proto3" json:"template_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryServiceConfig) Reset() {
	*x = RegistryServiceConfig{}
	mi := &file_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryServiceConfig) ProtoMessage() {}

func (x *RegistryServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryServiceConfig.ProtoReflect.Descriptor instead.
func (*RegistryServiceConfig) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryServiceConfig) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *RegistryServiceConfig) GetTemplateLinks() []*RegistryTemplateLink {
	if x != nil {
		return x.TemplateLinks
	}
	return nil
}

type RegistryTemplateLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	InboundId     string                 `protobuf:"bytes,3,opt,name=inbound_id,json=inboundId,proto3" json:"inbound_id,omitempty"`
	InboundName   string                 `protobuf:"bytes,4,opt,name=inbound_name,json=inboundName,proto3" json:"inbound_name,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Template      string                 `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryTemplateLink) Reset() {
	*x = RegistryTemplateLink{}
	mi := &file_registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryTemplateLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryTemplateLink) ProtoMessage() {}

func (x *RegistryTemplateLink) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryTemplateLink.ProtoReflect.Descriptor instead.
func (*RegistryTemplateLink) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryTemplateLink) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegistryTemplateLink) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegistryTemplateLink) GetInboundId() string {
	if x != nil {
		return x.InboundId
	}
	return ""
}

func (x *RegistryTemplateLink) GetInboundName() string {
	if x != nil {
		return x.InboundName
	}
	return ""
}

func (x *RegistryTemplateLink) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RegistryTemplateLink) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

type RegistryUpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *RegistryServiceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryUpdateConfigRequest) Reset() {
	*x = RegistryUpdateConfigRequest{}
	mi := &file_registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryUpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryUpdateConfigRequest) ProtoMessage() {}

func (x *RegistryUpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryUpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*RegistryUpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryUpdateConfigRequest) GetConfig() *RegistryServiceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegistryUpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *RegistryServiceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryUpdateConfigResponse) Reset() {
	*x = RegistryUpdateConfigResponse{}
	mi := &file_registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryUpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryUpdateConfigResponse) ProtoMessage() {}

func (x *RegistryUpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryUpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*RegistryUpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegistryUpdateConfigResponse) GetConfig() *RegistryServiceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegistryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryStatusRequest) Reset() {
	*x = RegistryStatusRequest{}
	mi := &file_registry_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryStatusRequest) ProtoMessage() {}

func (x *RegistryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryStatusRequest.ProtoReflect.Descriptor instead.
func (*RegistryStatusRequest) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{4}
}

type RegistryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Accounts      uint32                 `protobuf:"varint,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	TemplateLinks uint32                 `protobuf:"varint,3,opt,name=template_links,json=templateLinks,proto3" json:"template_links,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryStatusResponse) Reset() {
	*x = RegistryStatusResponse{}
	mi := &file_registry_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryStatusResponse) ProtoMessage() {}

func (x *RegistryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryStatusResponse.ProtoReflect.Descriptor instead.
func (*RegistryStatusResponse) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryStatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *RegistryStatusResponse) GetAccounts() uint32 {
	if x != nil {
		return x.Accounts
	}
	return 0
}

func (x *RegistryStatusResponse) GetTemplateLinks() uint32 {
	if x != nil {
		return x.TemplateLinks
	}
	return 0
}

func (x *RegistryStatusResponse) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_registry_registry_proto protoreflect.FileDescriptor

const file_registry_registry_proto_rawDesc = "" +
	"\n" +
	"\x17registry/registry.proto\x12\n" +
	"proxyswarm\x1a\raccount.proto\"\x91\x01\n" +
	"\x15RegistryServiceConfig\x12/\n" +
	"\baccounts\x18\x01 \x03(\v2\x13.proxyswarm.AccountR\baccounts\x12G\n" +
	"\x0etemplate_links\x18\x02 \x03(\v2 .proxyswarm.RegistryTemplateLinkR\rtemplateLinks\"\xc6\x01\n" +
	"\x14RegistryTemplateLink\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1d\n" +
	"\n" +
	"inbound_id\x18\x03 \x01(\tR\tinboundId\x12!\n" +
	"\finbound_name\x18\x04 \x01(\tR\vinboundName\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1a\n" +
	"\btemplate\x18\x06 \x01(\tR\btemplate\"X\n" +
	"\x1bRegistryUpdateConfigRequest\x129\n" +
	"\x06config\x18\x01 \x01(\v2!.proxyswarm.RegistryServiceConfigR\x06config\"Y\n" +
	"\x1cRegistryUpdateConfigResponse\x129\n" +
	"\x06config\x18\x01 \x01(\v2!.proxyswarm.RegistryServiceConfigR\x06config\"\x17\n" +
	"\x15RegistryStatusRequest\"\xa3\x01\n" +
	"\x16RegistryStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\rR\baccounts\x12%\n" +
	"\x0etemplate_links\x18\x03 \x01(\rR\rtemplateLinks\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix2\xcf\x01\n" +
	"\x19RegistryManagementService\x12a\n" +
	"\fUpdateConfig\x12'.proxyswarm.RegistryUpdateConfigRequest\x1a(.proxyswarm.RegistryUpdateConfigResponse\x12O\n" +
	"\x06Status\x12!.proxyswarm.RegistryStatusRequest\x1a\".proxyswarm.RegistryStatusResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_registry_registry_proto_rawDescOnce sync.Once
	file_registry_registry_proto_rawDescData []byte
)

func file_registry_registry_proto_rawDescGZIP() []byte {
	file_registry_registry_proto_rawDescOnce.Do(func() {
		file_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_registry_proto_rawDesc), len(file_registry_registry_proto_rawDesc)))
	})
	return file_registry_registry_proto_rawDescData
}

var file_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_registry_registry_proto_goTypes = []any{
	(*RegistryServiceConfig)(nil),        // 0: proxyswarm.RegistryServiceConfig
	(*RegistryTemplateLink)(nil),         // 1: proxyswarm.RegistryTemplateLink
	(*RegistryUpdateConfigRequest)(nil),  // 2: proxyswarm.RegistryUpdateConfigRequest
	(*RegistryUpdateConfigResponse)(nil), // 3: proxyswarm.RegistryUpdateConfigResponse
	(*RegistryStatusRequest)(nil),        // 4: proxyswarm.RegistryStatusRequest
	(*RegistryStatusResponse)(nil),       // 5: proxyswarm.RegistryStatusResponse
	(*Account)(nil),                      // 6: proxyswarm.Account
}
var file_registry_registry_proto_depIdxs = []int32{
	6, // 0: proxyswarm.RegistryServiceConfig.accounts:type_name -> proxyswarm.Account
	1, // 1: proxyswarm.RegistryServiceConfig.template_links:type_name -> proxyswarm.RegistryTemplateLink
	0, // 2: proxyswarm.RegistryUpdateConfigRequest.config:type_name -> proxyswarm.RegistryServiceConfig
	0, // 3: proxyswarm.RegistryUpdateConfigResponse.config:type_name -> proxyswarm.RegistryServiceConfig
	2, // 4: proxyswarm.RegistryManagementService.UpdateConfig:input_type -> proxyswarm.RegistryUpdateConfigRequest
	4, // 5: proxyswarm.RegistryManagementService.Status:input_type -> proxyswarm.RegistryStatusRequest
	3, // 6: proxyswarm.RegistryManagementService.UpdateConfig:output_type -> proxyswarm.RegistryUpdateConfigResponse
	5, // 7: proxyswarm.RegistryManagementService.Status:output_type -> proxyswarm.RegistryStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_registry_registry_proto_init() }
func file_registry_registry_proto_init() {
	if File_registry_registry_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_registry_proto_rawDesc), len(file_registry_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_registry_proto_goTypes,
		DependencyIndexes: file_registry_registry_proto_depIdxs,
		MessageInfos:      file_registry_registry_proto_msgTypes,
	}.Build()
	File_registry_registry_proto = out.File
	file_registry_registry_proto_goTypes = nil
	file_registry_registry_proto_depIdxs = nil
}
