syntax = "proto3";
package proxyswarm;
option go_package = "./pb";

import "account.proto";

service RegistryManagementService {
    rpc UpdateConfig(RegistryUpdateConfigRequest) returns (RegistryUpdateConfigResponse);
    rpc Status(RegistryStatusRequest) returns (RegistryStatusResponse);
}

message RegistryServiceConfig {
    repeated Account accounts = 1;
    repeated RegistryTemplateLink template_links = 2;
    string brand = 3;
}

message RegistryTemplateLink {
    string node_id = 1;
    string node_name = 2;
    string inbound_id = 3;
    string inbound_name = 4;
    string protocol = 5;
    string template = 6;
    repeated string groups = 7;
}

message RegistryUpdateConfigRequest {
    RegistryServiceConfig config = 1;
}

message RegistryUpdateConfigResponse {
    RegistryServiceConfig config = 1;
}

message RegistryStatusRequest {}

message RegistryStatusResponse {
    bool configured = 1;
    uint32 accounts = 2;
    uint32 template_links = 3;
    int64 updated_at_unix = 4;
}
