// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	ExpiryTime    int64                  `protobuf:"varint,4,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"` // Unix timestamp
	AccessId      string                 `protobuf:"bytes,5,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`        // Used as UUID for VLESS/etc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Account) GetExpiryTime() int64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *Account) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

type HardwareStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsed       uint64                 `protobuf:"varint,2,opt,name=ram_used,json=ramUsed,proto3" json:"ram_used,omitempty"`
	RamTotal      uint64                 `protobuf:"varint,3,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	Uptime        uint64                 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareStats) Reset() {
	*x = HardwareStats{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareStats) ProtoMessage() {}

func (x *HardwareStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareStats.ProtoReflect.Descriptor instead.
func (*HardwareStats) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *HardwareStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HardwareStats) GetRamUsed() uint64 {
	if x != nil {
		return x.RamUsed
	}
	return 0
}

func (x *HardwareStats) GetRamTotal() uint64 {
	if x != nil {
		return x.RamTotal
	}
	return 0
}

func (x *HardwareStats) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *HardwareStats) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

type TrafficStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rx            uint64                 `protobuf:"varint,1,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            uint64                 `protobuf:"varint,2,opt,name=tx,proto3" json:"tx,omitempty"`
	RxRate        float64                `protobuf:"fixed64,3,opt,name=rx_rate,json=rxRate,proto3" json:"rx_rate,omitempty"`
	TxRate        float64                `protobuf:"fixed64,4,opt,name=tx_rate,json=txRate,proto3" json:"tx_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficStats) Reset() {
	*x = TrafficStats{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficStats) ProtoMessage() {}

func (x *TrafficStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficStats.ProtoReflect.Descriptor instead.
func (*TrafficStats) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficStats) GetRx() uint64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *TrafficStats) GetTx() uint64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

func (x *TrafficStats) GetRxRate() float64 {
	if x != nil {
		return x.RxRate
	}
	return 0
}

func (x *TrafficStats) GetTxRate() float64 {
	if x != nil {
		return x.TxRate
	}
	return 0
}

type ConnectionStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tcp           uint32                 `protobuf:"varint,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Udp           uint32                 `protobuf:"varint,2,opt,name=udp,proto3" json:"udp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStats) Reset() {
	*x = ConnectionStats{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStats) ProtoMessage() {}

func (x *ConnectionStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStats.ProtoReflect.Descriptor instead.
func (*ConnectionStats) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionStats) GetTcp() uint32 {
	if x != nil {
		return x.Tcp
	}
	return 0
}

func (x *ConnectionStats) GetUdp() uint32 {
	if x != nil {
		return x.Udp
	}
	return 0
}

type UserSessionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionStatus) Reset() {
	*x = UserSessionStatus{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionStatus) ProtoMessage() {}

func (x *UserSessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionStatus.ProtoReflect.Descriptor instead.
func (*UserSessionStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserSessionStatus) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserSessionStatus) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type InboundStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Traffic       *TrafficStats          `protobuf:"bytes,2,opt,name=traffic,proto3" json:"traffic,omitempty"`
	Connections   *ConnectionStats       `protobuf:"bytes,3,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundStatus) Reset() {
	*x = InboundStatus{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundStatus) ProtoMessage() {}

func (x *InboundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundStatus.ProtoReflect.Descriptor instead.
func (*InboundStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *InboundStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundStatus) GetTraffic() *TrafficStats {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *InboundStatus) GetConnections() *ConnectionStats {
	if x != nil {
		return x.Connections
	}
	return nil
}

type AccountStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Traffic       *TrafficStats          `protobuf:"bytes,2,opt,name=traffic,proto3" json:"traffic,omitempty"`
	Online        uint32                 `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Sessions      []*UserSessionStatus   `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountStatus) Reset() {
	*x = AccountStatus{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStatus) ProtoMessage() {}

func (x *AccountStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStatus.ProtoReflect.Descriptor instead.
func (*AccountStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *AccountStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountStatus) GetTraffic() *TrafficStats {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *AccountStatus) GetOnline() uint32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *AccountStatus) GetSessions() []*UserSessionStatus {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type OutboundStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Traffic            *TrafficStats          `protobuf:"bytes,3,opt,name=traffic,proto3" json:"traffic,omitempty"`
	ExcludedFromTotals bool                   `protobuf:"varint,4,opt,name=excluded_from_totals,json=excludedFromTotals,proto3" json:"excluded_from_totals,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OutboundStatus) Reset() {
	*x = OutboundStatus{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundStatus) ProtoMessage() {}

func (x *OutboundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundStatus.ProtoReflect.Descriptor instead.
func (*OutboundStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *OutboundStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutboundStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundStatus) GetTraffic() *TrafficStats {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *OutboundStatus) GetExcludedFromTotals() bool {
	if x != nil {
		return x.ExcludedFromTotals
	}
	return false
}

type NodeStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hardware             *HardwareStats         `protobuf:"bytes,1,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Inbounds             []*InboundStatus       `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Accounts             []*AccountStatus       `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Outbounds            []*OutboundStatus      `protobuf:"bytes,4,rep,name=outbounds,proto3" json:"outbounds,omitempty"`
	TotalInboundTraffic  *TrafficStats          `protobuf:"bytes,5,opt,name=total_inbound_traffic,json=totalInboundTraffic,proto3" json:"total_inbound_traffic,omitempty"`
	TotalOutboundTraffic *TrafficStats          `protobuf:"bytes,6,opt,name=total_outbound_traffic,json=totalOutboundTraffic,proto3" json:"total_outbound_traffic,omitempty"`
	Connections          *ConnectionStats       `protobuf:"bytes,7,opt,name=connections,proto3" json:"connections,omitempty"`
	SampleWindowSeconds  uint32                 `protobuf:"varint,8,opt,name=sample_window_seconds,json=sampleWindowSeconds,proto3" json:"sample_window_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatus) GetHardware() *HardwareStats {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *NodeStatus) GetInbounds() []*InboundStatus {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *NodeStatus) GetAccounts() []*AccountStatus {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *NodeStatus) GetOutbounds() []*OutboundStatus {
	if x != nil {
		return x.Outbounds
	}
	return nil
}

func (x *NodeStatus) GetTotalInboundTraffic() *TrafficStats {
	if x != nil {
		return x.TotalInboundTraffic
	}
	return nil
}

func (x *NodeStatus) GetTotalOutboundTraffic() *TrafficStats {
	if x != nil {
		return x.TotalOutboundTraffic
	}
	return nil
}

func (x *NodeStatus) GetConnections() *ConnectionStats {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *NodeStatus) GetSampleWindowSeconds() uint32 {
	if x != nil {
		return x.SampleWindowSeconds
	}
	return 0
}

type CertificateConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CertType        string                 `protobuf:"bytes,3,opt,name=cert_type,json=certType,proto3" json:"cert_type,omitempty"`
	AcmeType        string                 `protobuf:"bytes,4,opt,name=acme_type,json=acmeType,proto3" json:"acme_type,omitempty"`
	AcmeCa          string                 `protobuf:"bytes,5,opt,name=acme_ca,json=acmeCa,proto3" json:"acme_ca,omitempty"`
	AcmeEmail       string                 `protobuf:"bytes,6,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	AcmeDomain      string                 `protobuf:"bytes,7,opt,name=acme_domain,json=acmeDomain,proto3" json:"acme_domain,omitempty"`
	CertificatePath string                 `protobuf:"bytes,8,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	KeyPath         string                 `protobuf:"bytes,9,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	AcmePort        int32                  `protobuf:"varint,10,opt,name=acme_port,json=acmePort,proto3" json:"acme_port,omitempty"`
	AcmeHttpPort    int32                  `protobuf:"varint,11,opt,name=acme_http_port,json=acmeHttpPort,proto3" json:"acme_http_port,omitempty"`
	CertificatePem  string                 `protobuf:"bytes,12,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	KeyPem          string                 `protobuf:"bytes,13,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateConfig) Reset() {
	*x = CertificateConfig{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateConfig) ProtoMessage() {}

func (x *CertificateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateConfig.ProtoReflect.Descriptor instead.
func (*CertificateConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *CertificateConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateConfig) GetCertType() string {
	if x != nil {
		return x.CertType
	}
	return ""
}

func (x *CertificateConfig) GetAcmeType() string {
	if x != nil {
		return x.AcmeType
	}
	return ""
}

func (x *CertificateConfig) GetAcmeCa() string {
	if x != nil {
		return x.AcmeCa
	}
	return ""
}

func (x *CertificateConfig) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

func (x *CertificateConfig) GetAcmeDomain() string {
	if x != nil {
		return x.AcmeDomain
	}
	return ""
}

func (x *CertificateConfig) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *CertificateConfig) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *CertificateConfig) GetAcmePort() int32 {
	if x != nil {
		return x.AcmePort
	}
	return 0
}

func (x *CertificateConfig) GetAcmeHttpPort() int32 {
	if x != nil {
		return x.AcmeHttpPort
	}
	return 0
}

func (x *CertificateConfig) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *CertificateConfig) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

type TLSConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServerName      string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	CertificateName string                 `protobuf:"bytes,3,opt,name=certificate_name,json=certificateName,proto3" json:"certificate_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfig.ProtoReflect.Descriptor instead.
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *TLSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TLSConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSConfig) GetCertificateName() string {
	if x != nil {
		return x.CertificateName
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"proxyswarm\"\x8c\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12\x1f\n" +
	"\vexpiry_time\x18\x04 \x01(\x03R\n" +
	"expiryTime\x12\x1b\n" +
	"\taccess_id\x18\x05 \x01(\tR\baccessId\"\x99\x01\n" +
	"\rHardwareStats\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12\x19\n" +
	"\bram_used\x18\x02 \x01(\x04R\aramUsed\x12\x1b\n" +
	"\tram_total\x18\x03 \x01(\x04R\bramTotal\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x04R\x06uptime\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\"`\n" +
	"\fTrafficStats\x12\x0e\n" +
	"\x02rx\x18\x01 \x01(\x04R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x02 \x01(\x04R\x02tx\x12\x17\n" +
	"\arx_rate\x18\x03 \x01(\x01R\x06rxRate\x12\x17\n" +
	"\atx_rate\x18\x04 \x01(\x01R\x06txRate\"5\n" +
	"\x0fConnectionStats\x12\x10\n" +
	"\x03tcp\x18\x01 \x01(\rR\x03tcp\x12\x10\n" +
	"\x03udp\x18\x02 \x01(\rR\x03udp\"B\n" +
	"\x11UserSessionStatus\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\x96\x01\n" +
	"\rInboundStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\atraffic\x18\x02 \x01(\v2\x18.proxyswarm.TrafficStatsR\atraffic\x12=\n" +
	"\vconnections\x18\x03 \x01(\v2\x1b.proxyswarm.ConnectionStatsR\vconnections\"\xaa\x01\n" +
	"\rAccountStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\atraffic\x18\x02 \x01(\v2\x18.proxyswarm.TrafficStatsR\atraffic\x12\x16\n" +
	"\x06online\x18\x03 \x01(\rR\x06online\x129\n" +
	"\bsessions\x18\x04 \x03(\v2\x1d.proxyswarm.UserSessionStatusR\bsessions\"\x9e\x01\n" +
	"\x0eOutboundStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\atraffic\x18\x03 \x01(\v2\x18.proxyswarm.TrafficStatsR\atraffic\x120\n" +
	"\x14excluded_from_totals\x18\x04 \x01(\bR\x12excludedFromTotals\"\xfc\x03\n" +
	"\n" +
	"NodeStatus\x125\n" +
	"\bhardware\x18\x01 \x01(\v2\x19.proxyswarm.HardwareStatsR\bhardware\x125\n" +
	"\binbounds\x18\x02 \x03(\v2\x19.proxyswarm.InboundStatusR\binbounds\x125\n" +
	"\baccounts\x18\x03 \x03(\v2\x19.proxyswarm.AccountStatusR\baccounts\x128\n" +
	"\toutbounds\x18\x04 \x03(\v2\x1a.proxyswarm.OutboundStatusR\toutbounds\x12L\n" +
	"\x15total_inbound_traffic\x18\x05 \x01(\v2\x18.proxyswarm.TrafficStatsR\x13totalInboundTraffic\x12N\n" +
	"\x16total_outbound_traffic\x18\x06 \x01(\v2\x18.proxyswarm.TrafficStatsR\x14totalOutboundTraffic\x12=\n" +
	"\vconnections\x18\a \x01(\v2\x1b.proxyswarm.ConnectionStatsR\vconnections\x122\n" +
	"\x15sample_window_seconds\x18\b \x01(\rR\x13sampleWindowSeconds\"\x95\x03\n" +
	"\x11CertificateConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcert_type\x18\x03 \x01(\tR\bcertType\x12\x1b\n" +
	"\tacme_type\x18\x04 \x01(\tR\bacmeType\x12\x17\n" +
	"\aacme_ca\x18\x05 \x01(\tR\x06acmeCa\x12\x1d\n" +
	"\n" +
	"acme_email\x18\x06 \x01(\tR\tacmeEmail\x12\x1f\n" +
	"\vacme_domain\x18\a \x01(\tR\n" +
	"acmeDomain\x12)\n" +
	"\x10certificate_path\x18\b \x01(\tR\x0fcertificatePath\x12\x19\n" +
	"\bkey_path\x18\t \x01(\tR\akeyPath\x12\x1b\n" +
	"\tacme_port\x18\n" +
	" \x01(\x05R\bacmePort\x12$\n" +
	"\x0eacme_http_port\x18\v \x01(\x05R\facmeHttpPort\x12'\n" +
	"\x0fcertificate_pem\x18\f \x01(\tR\x0ecertificatePem\x12\x17\n" +
	"\akey_pem\x18\r \x01(\tR\x06keyPem\"q\n" +
	"\tTLSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12)\n" +
	"\x10certificate_name\x18\x03 \x01(\tR\x0fcertificateNameB\x06Z\x04./pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_goTypes = []any{
	(*Account)(nil),           // 0: proxyswarm.Account
	(*HardwareStats)(nil),     // 1: proxyswarm.HardwareStats
	(*TrafficStats)(nil),      // 2: proxyswarm.TrafficStats
	(*ConnectionStats)(nil),   // 3: proxyswarm.ConnectionStats
	(*UserSessionStatus)(nil), // 4: proxyswarm.UserSessionStatus
	(*InboundStatus)(nil),     // 5: proxyswarm.InboundStatus
	(*AccountStatus)(nil),     // 6: proxyswarm.AccountStatus
	(*OutboundStatus)(nil),    // 7: proxyswarm.OutboundStatus
	(*NodeStatus)(nil),        // 8: proxyswarm.NodeStatus
	(*CertificateConfig)(nil), // 9: proxyswarm.CertificateConfig
	(*TLSConfig)(nil),         // 10: proxyswarm.TLSConfig
}
var file_common_proto_depIdxs = []int32{
	2,  // 0: proxyswarm.InboundStatus.traffic:type_name -> proxyswarm.TrafficStats
	3,  // 1: proxyswarm.InboundStatus.connections:type_name -> proxyswarm.ConnectionStats
	2,  // 2: proxyswarm.AccountStatus.traffic:type_name -> proxyswarm.TrafficStats
	4,  // 3: proxyswarm.AccountStatus.sessions:type_name -> proxyswarm.UserSessionStatus
	2,  // 4: proxyswarm.OutboundStatus.traffic:type_name -> proxyswarm.TrafficStats
	1,  // 5: proxyswarm.NodeStatus.hardware:type_name -> proxyswarm.HardwareStats
	5,  // 6: proxyswarm.NodeStatus.inbounds:type_name -> proxyswarm.InboundStatus
	6,  // 7: proxyswarm.NodeStatus.accounts:type_name -> proxyswarm.AccountStatus
	7,  // 8: proxyswarm.NodeStatus.outbounds:type_name -> proxyswarm.OutboundStatus
	2,  // 9: proxyswarm.NodeStatus.total_inbound_traffic:type_name -> proxyswarm.TrafficStats
	2,  // 10: proxyswarm.NodeStatus.total_outbound_traffic:type_name -> proxyswarm.TrafficStats
	3,  // 11: proxyswarm.NodeStatus.connections:type_name -> proxyswarm.ConnectionStats
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
