// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/naiveproxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NaiveProxyConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Network               string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"` // "tcp", "udp", or empty for both
	QuicCongestionControl string                 `protobuf:"bytes,2,opt,name=quic_congestion_control,json=quicCongestionControl,proto3" json:"quic_congestion_control,omitempty"`
	Tls                   *TLSConfig             `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NaiveProxyConfig) Reset() {
	*x = NaiveProxyConfig{}
	mi := &file_node_naiveproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NaiveProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NaiveProxyConfig) ProtoMessage() {}

func (x *NaiveProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_naiveproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NaiveProxyConfig.ProtoReflect.Descriptor instead.
func (*NaiveProxyConfig) Descriptor() ([]byte, []int) {
	return file_node_naiveproxy_proto_rawDescGZIP(), []int{0}
}

func (x *NaiveProxyConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NaiveProxyConfig) GetQuicCongestionControl() string {
	if x != nil {
		return x.QuicCongestionControl
	}
	return ""
}

func (x *NaiveProxyConfig) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_node_naiveproxy_proto protoreflect.FileDescriptor

const file_node_naiveproxy_proto_rawDesc = "" +
	"\n" +
	"\x15node/naiveproxy.proto\x12\n" +
	"proxyswarm\x1a\x11node/common.proto\"\x8d\x01\n" +
	"\x10NaiveProxyConfig\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x126\n" +
	"\x17quic_congestion_control\x18\x02 \x01(\tR\x15quicCongestionControl\x12'\n" +
	"\x03tls\x18\x03 \x01(\v2\x15.proxyswarm.TLSConfigR\x03tlsB\x06Z\x04./pbb\x06proto3"

var (
	file_node_naiveproxy_proto_rawDescOnce sync.Once
	file_node_naiveproxy_proto_rawDescData []byte
)

func file_node_naiveproxy_proto_rawDescGZIP() []byte {
	file_node_naiveproxy_proto_rawDescOnce.Do(func() {
		file_node_naiveproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_naiveproxy_proto_rawDesc), len(file_node_naiveproxy_proto_rawDesc)))
	})
	return file_node_naiveproxy_proto_rawDescData
}

var file_node_naiveproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_naiveproxy_proto_goTypes = []any{
	(*NaiveProxyConfig)(nil), // 0: proxyswarm.NaiveProxyConfig
	(*TLSConfig)(nil),        // 1: proxyswarm.TLSConfig
}
var file_node_naiveproxy_proto_depIdxs = []int32{
	1, // 0: proxyswarm.NaiveProxyConfig.tls:type_name -> proxyswarm.TLSConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_naiveproxy_proto_init() }
func file_node_naiveproxy_proto_init() {
	if File_node_naiveproxy_proto != nil {
		return
	}
	file_node_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_naiveproxy_proto_rawDesc), len(file_node_naiveproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_naiveproxy_proto_goTypes,
		DependencyIndexes: file_node_naiveproxy_proto_depIdxs,
		MessageInfos:      file_node_naiveproxy_proto_msgTypes,
	}.Build()
	File_node_naiveproxy_proto = out.File
	file_node_naiveproxy_proto_goTypes = nil
	file_node_naiveproxy_proto_depIdxs = nil
}
