// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/reverseproxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReverseProxyConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // "bridge" or "portal"
	Tag               string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Domain            string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	BridgeOutboundTag string                 `protobuf:"bytes,4,opt,name=bridge_outbound_tag,json=bridgeOutboundTag,proto3" json:"bridge_outbound_tag,omitempty"`
	TargetOutboundTag string                 `protobuf:"bytes,5,opt,name=target_outbound_tag,json=targetOutboundTag,proto3" json:"target_outbound_tag,omitempty"`
	PortalInboundTag  string                 `protobuf:"bytes,6,opt,name=portal_inbound_tag,json=portalInboundTag,proto3" json:"portal_inbound_tag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReverseProxyConfig) Reset() {
	*x = ReverseProxyConfig{}
	mi := &file_node_reverseproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseProxyConfig) ProtoMessage() {}

func (x *ReverseProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_reverseproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseProxyConfig.ProtoReflect.Descriptor instead.
func (*ReverseProxyConfig) Descriptor() ([]byte, []int) {
	return file_node_reverseproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ReverseProxyConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ReverseProxyConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ReverseProxyConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ReverseProxyConfig) GetBridgeOutboundTag() string {
	if x != nil {
		return x.BridgeOutboundTag
	}
	return ""
}

func (x *ReverseProxyConfig) GetTargetOutboundTag() string {
	if x != nil {
		return x.TargetOutboundTag
	}
	return ""
}

func (x *ReverseProxyConfig) GetPortalInboundTag() string {
	if x != nil {
		return x.PortalInboundTag
	}
	return ""
}

var File_node_reverseproxy_proto protoreflect.FileDescriptor

const file_node_reverseproxy_proto_rawDesc = "" +
	"\n" +
	"\x17node/reverseproxy.proto\x12\n" +
	"proxyswarm\"\xe0\x01\n" +
	"\x12ReverseProxyConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12.\n" +
	"\x13bridge_outbound_tag\x18\x04 \x01(\tR\x11bridgeOutboundTag\x12.\n" +
	"\x13target_outbound_tag\x18\x05 \x01(\tR\x11targetOutboundTag\x12,\n" +
	"\x12portal_inbound_tag\x18\x06 \x01(\tR\x10portalInboundTagB\x06Z\x04./pbb\x06proto3"

var (
	file_node_reverseproxy_proto_rawDescOnce sync.Once
	file_node_reverseproxy_proto_rawDescData []byte
)

func file_node_reverseproxy_proto_rawDescGZIP() []byte {
	file_node_reverseproxy_proto_rawDescOnce.Do(func() {
		file_node_reverseproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_reverseproxy_proto_rawDesc), len(file_node_reverseproxy_proto_rawDesc)))
	})
	return file_node_reverseproxy_proto_rawDescData
}

var file_node_reverseproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_reverseproxy_proto_goTypes = []any{
	(*ReverseProxyConfig)(nil), // 0: proxyswarm.ReverseProxyConfig
}
var file_node_reverseproxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_reverseproxy_proto_init() }
func file_node_reverseproxy_proto_init() {
	if File_node_reverseproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_reverseproxy_proto_rawDesc), len(file_node_reverseproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_reverseproxy_proto_goTypes,
		DependencyIndexes: file_node_reverseproxy_proto_depIdxs,
		MessageInfos:      file_node_reverseproxy_proto_msgTypes,
	}.Build()
	File_node_reverseproxy_proto = out.File
	file_node_reverseproxy_proto_goTypes = nil
	file_node_reverseproxy_proto_depIdxs = nil
}
