// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/reverseproxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VlessReverseProxyConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tag              string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	PortalInboundTag string                 `protobuf:"bytes,2,opt,name=portal_inbound_tag,json=portalInboundTag,proto3" json:"portal_inbound_tag,omitempty"`
	PortalUserId     string                 `protobuf:"bytes,3,opt,name=portal_user_id,json=portalUserId,proto3" json:"portal_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VlessReverseProxyConfig) Reset() {
	*x = VlessReverseProxyConfig{}
	mi := &file_node_reverseproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessReverseProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessReverseProxyConfig) ProtoMessage() {}

func (x *VlessReverseProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_reverseproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessReverseProxyConfig.ProtoReflect.Descriptor instead.
func (*VlessReverseProxyConfig) Descriptor() ([]byte, []int) {
	return file_node_reverseproxy_proto_rawDescGZIP(), []int{0}
}

func (x *VlessReverseProxyConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VlessReverseProxyConfig) GetPortalInboundTag() string {
	if x != nil {
		return x.PortalInboundTag
	}
	return ""
}

func (x *VlessReverseProxyConfig) GetPortalUserId() string {
	if x != nil {
		return x.PortalUserId
	}
	return ""
}

var File_node_reverseproxy_proto protoreflect.FileDescriptor

const file_node_reverseproxy_proto_rawDesc = "" +
	"\n" +
	"\x17node/reverseproxy.proto\x12\n" +
	"proxyswarm\"\x7f\n" +
	"\x17VlessReverseProxyConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12,\n" +
	"\x12portal_inbound_tag\x18\x02 \x01(\tR\x10portalInboundTag\x12$\n" +
	"\x0eportal_user_id\x18\x03 \x01(\tR\fportalUserIdB\x06Z\x04./pbb\x06proto3"

var (
	file_node_reverseproxy_proto_rawDescOnce sync.Once
	file_node_reverseproxy_proto_rawDescData []byte
)

func file_node_reverseproxy_proto_rawDescGZIP() []byte {
	file_node_reverseproxy_proto_rawDescOnce.Do(func() {
		file_node_reverseproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_reverseproxy_proto_rawDesc), len(file_node_reverseproxy_proto_rawDesc)))
	})
	return file_node_reverseproxy_proto_rawDescData
}

var file_node_reverseproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_reverseproxy_proto_goTypes = []any{
	(*VlessReverseProxyConfig)(nil), // 0: proxyswarm.VlessReverseProxyConfig
}
var file_node_reverseproxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_reverseproxy_proto_init() }
func file_node_reverseproxy_proto_init() {
	if File_node_reverseproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_reverseproxy_proto_rawDesc), len(file_node_reverseproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_reverseproxy_proto_goTypes,
		DependencyIndexes: file_node_reverseproxy_proto_depIdxs,
		MessageInfos:      file_node_reverseproxy_proto_msgTypes,
	}.Build()
	File_node_reverseproxy_proto = out.File
	file_node_reverseproxy_proto_goTypes = nil
	file_node_reverseproxy_proto_depIdxs = nil
}
