// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: socks5.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Socks5InboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UdpEnabled    bool                   `protobuf:"varint,3,opt,name=udp_enabled,json=udpEnabled,proto3" json:"udp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5InboundConfig) Reset() {
	*x = Socks5InboundConfig{}
	mi := &file_socks5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5InboundConfig) ProtoMessage() {}

func (x *Socks5InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_socks5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5InboundConfig.ProtoReflect.Descriptor instead.
func (*Socks5InboundConfig) Descriptor() ([]byte, []int) {
	return file_socks5_proto_rawDescGZIP(), []int{0}
}

func (x *Socks5InboundConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Socks5InboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Socks5InboundConfig) GetUdpEnabled() bool {
	if x != nil {
		return x.UdpEnabled
	}
	return false
}

type Socks5OutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5OutboundConfig) Reset() {
	*x = Socks5OutboundConfig{}
	mi := &file_socks5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5OutboundConfig) ProtoMessage() {}

func (x *Socks5OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_socks5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5OutboundConfig.ProtoReflect.Descriptor instead.
func (*Socks5OutboundConfig) Descriptor() ([]byte, []int) {
	return file_socks5_proto_rawDescGZIP(), []int{1}
}

func (x *Socks5OutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Socks5OutboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Socks5OutboundConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Socks5OutboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_socks5_proto protoreflect.FileDescriptor

const file_socks5_proto_rawDesc = "" +
	"\n" +
	"\fsocks5.proto\x12\n" +
	"proxyswarm\"n\n" +
	"\x13Socks5InboundConfig\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vudp_enabled\x18\x03 \x01(\bR\n" +
	"udpEnabled\"z\n" +
	"\x14Socks5OutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpasswordB\x06Z\x04./pbb\x06proto3"

var (
	file_socks5_proto_rawDescOnce sync.Once
	file_socks5_proto_rawDescData []byte
)

func file_socks5_proto_rawDescGZIP() []byte {
	file_socks5_proto_rawDescOnce.Do(func() {
		file_socks5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socks5_proto_rawDesc), len(file_socks5_proto_rawDesc)))
	})
	return file_socks5_proto_rawDescData
}

var file_socks5_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_socks5_proto_goTypes = []any{
	(*Socks5InboundConfig)(nil),  // 0: proxyswarm.Socks5InboundConfig
	(*Socks5OutboundConfig)(nil), // 1: proxyswarm.Socks5OutboundConfig
}
var file_socks5_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socks5_proto_init() }
func file_socks5_proto_init() {
	if File_socks5_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socks5_proto_rawDesc), len(file_socks5_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socks5_proto_goTypes,
		DependencyIndexes: file_socks5_proto_depIdxs,
		MessageInfos:      file_socks5_proto_msgTypes,
	}.Build()
	File_socks5_proto = out.File
	file_socks5_proto_goTypes = nil
	file_socks5_proto_depIdxs = nil
}
