// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/tproxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TProxyConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Network              string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"` // tcp, udp, or tcp,udp
	SniffingEnabled      bool                   `protobuf:"varint,2,opt,name=sniffing_enabled,json=sniffingEnabled,proto3" json:"sniffing_enabled,omitempty"`
	SniffingDestOverride []string               `protobuf:"bytes,3,rep,name=sniffing_dest_override,json=sniffingDestOverride,proto3" json:"sniffing_dest_override,omitempty"`
	SniffingRouteOnly    bool                   `protobuf:"varint,4,opt,name=sniffing_route_only,json=sniffingRouteOnly,proto3" json:"sniffing_route_only,omitempty"`
	SocketMark           int32                  `protobuf:"varint,5,opt,name=socket_mark,json=socketMark,proto3" json:"socket_mark,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TProxyConfig) Reset() {
	*x = TProxyConfig{}
	mi := &file_node_tproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TProxyConfig) ProtoMessage() {}

func (x *TProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_tproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TProxyConfig.ProtoReflect.Descriptor instead.
func (*TProxyConfig) Descriptor() ([]byte, []int) {
	return file_node_tproxy_proto_rawDescGZIP(), []int{0}
}

func (x *TProxyConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TProxyConfig) GetSniffingEnabled() bool {
	if x != nil {
		return x.SniffingEnabled
	}
	return false
}

func (x *TProxyConfig) GetSniffingDestOverride() []string {
	if x != nil {
		return x.SniffingDestOverride
	}
	return nil
}

func (x *TProxyConfig) GetSniffingRouteOnly() bool {
	if x != nil {
		return x.SniffingRouteOnly
	}
	return false
}

func (x *TProxyConfig) GetSocketMark() int32 {
	if x != nil {
		return x.SocketMark
	}
	return 0
}

var File_node_tproxy_proto protoreflect.FileDescriptor

const file_node_tproxy_proto_rawDesc = "" +
	"\n" +
	"\x11node/tproxy.proto\x12\n" +
	"proxyswarm\"\xda\x01\n" +
	"\fTProxyConfig\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12)\n" +
	"\x10sniffing_enabled\x18\x02 \x01(\bR\x0fsniffingEnabled\x124\n" +
	"\x16sniffing_dest_override\x18\x03 \x03(\tR\x14sniffingDestOverride\x12.\n" +
	"\x13sniffing_route_only\x18\x04 \x01(\bR\x11sniffingRouteOnly\x12\x1f\n" +
	"\vsocket_mark\x18\x05 \x01(\x05R\n" +
	"socketMarkB\x06Z\x04./pbb\x06proto3"

var (
	file_node_tproxy_proto_rawDescOnce sync.Once
	file_node_tproxy_proto_rawDescData []byte
)

func file_node_tproxy_proto_rawDescGZIP() []byte {
	file_node_tproxy_proto_rawDescOnce.Do(func() {
		file_node_tproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_tproxy_proto_rawDesc), len(file_node_tproxy_proto_rawDesc)))
	})
	return file_node_tproxy_proto_rawDescData
}

var file_node_tproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_tproxy_proto_goTypes = []any{
	(*TProxyConfig)(nil), // 0: proxyswarm.TProxyConfig
}
var file_node_tproxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_tproxy_proto_init() }
func file_node_tproxy_proto_init() {
	if File_node_tproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_tproxy_proto_rawDesc), len(file_node_tproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_tproxy_proto_goTypes,
		DependencyIndexes: file_node_tproxy_proto_depIdxs,
		MessageInfos:      file_node_tproxy_proto_msgTypes,
	}.Build()
	File_node_tproxy_proto = out.File
	file_node_tproxy_proto_goTypes = nil
	file_node_tproxy_proto_depIdxs = nil
}
