// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/trojan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrojanInboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	Fallback      string                 `protobuf:"bytes,3,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrojanInboundConfig) Reset() {
	*x = TrojanInboundConfig{}
	mi := &file_node_trojan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrojanInboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrojanInboundConfig) ProtoMessage() {}

func (x *TrojanInboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_trojan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrojanInboundConfig.ProtoReflect.Descriptor instead.
func (*TrojanInboundConfig) Descriptor() ([]byte, []int) {
	return file_node_trojan_proto_rawDescGZIP(), []int{0}
}

func (x *TrojanInboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TrojanInboundConfig) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *TrojanInboundConfig) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

type TrojanOutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	TlsEnabled    bool                   `protobuf:"varint,4,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	Sni           string                 `protobuf:"bytes,5,opt,name=sni,proto3" json:"sni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrojanOutboundConfig) Reset() {
	*x = TrojanOutboundConfig{}
	mi := &file_node_trojan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrojanOutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrojanOutboundConfig) ProtoMessage() {}

func (x *TrojanOutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_trojan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrojanOutboundConfig.ProtoReflect.Descriptor instead.
func (*TrojanOutboundConfig) Descriptor() ([]byte, []int) {
	return file_node_trojan_proto_rawDescGZIP(), []int{1}
}

func (x *TrojanOutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *TrojanOutboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TrojanOutboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TrojanOutboundConfig) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

func (x *TrojanOutboundConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

var File_node_trojan_proto protoreflect.FileDescriptor

const file_node_trojan_proto_rawDesc = "" +
	"\n" +
	"\x11node/trojan.proto\x12\n" +
	"proxyswarm\x1a\x11node/common.proto\"v\n" +
	"\x13TrojanInboundConfig\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12'\n" +
	"\x03tls\x18\x02 \x01(\v2\x15.proxyswarm.TLSConfigR\x03tls\x12\x1a\n" +
	"\bfallback\x18\x03 \x01(\tR\bfallback\"\x91\x01\n" +
	"\x14TrojanOutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1f\n" +
	"\vtls_enabled\x18\x04 \x01(\bR\n" +
	"tlsEnabled\x12\x10\n" +
	"\x03sni\x18\x05 \x01(\tR\x03sniB\x06Z\x04./pbb\x06proto3"

var (
	file_node_trojan_proto_rawDescOnce sync.Once
	file_node_trojan_proto_rawDescData []byte
)

func file_node_trojan_proto_rawDescGZIP() []byte {
	file_node_trojan_proto_rawDescOnce.Do(func() {
		file_node_trojan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_trojan_proto_rawDesc), len(file_node_trojan_proto_rawDesc)))
	})
	return file_node_trojan_proto_rawDescData
}

var file_node_trojan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_trojan_proto_goTypes = []any{
	(*TrojanInboundConfig)(nil),  // 0: proxyswarm.TrojanInboundConfig
	(*TrojanOutboundConfig)(nil), // 1: proxyswarm.TrojanOutboundConfig
	(*TLSConfig)(nil),            // 2: proxyswarm.TLSConfig
}
var file_node_trojan_proto_depIdxs = []int32{
	2, // 0: proxyswarm.TrojanInboundConfig.tls:type_name -> proxyswarm.TLSConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_trojan_proto_init() }
func file_node_trojan_proto_init() {
	if File_node_trojan_proto != nil {
		return
	}
	file_node_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_trojan_proto_rawDesc), len(file_node_trojan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_trojan_proto_goTypes,
		DependencyIndexes: file_node_trojan_proto_depIdxs,
		MessageInfos:      file_node_trojan_proto_msgTypes,
	}.Build()
	File_node_trojan_proto = out.File
	file_node_trojan_proto_goTypes = nil
	file_node_trojan_proto_depIdxs = nil
}
