// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wireguard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WireGuardConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey     string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Addresses      []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Peers          []*WireGuardPeer       `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	Mtu            int32                  `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Workers        int32                  `protobuf:"varint,5,opt,name=workers,proto3" json:"workers,omitempty"`
	Reserved       []uint32               `protobuf:"varint,6,rep,packed,name=reserved,proto3" json:"reserved,omitempty"` // 3 bytes
	DomainStrategy string                 `protobuf:"bytes,7,opt,name=domain_strategy,json=domainStrategy,proto3" json:"domain_strategy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WireGuardConfig) Reset() {
	*x = WireGuardConfig{}
	mi := &file_wireguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardConfig) ProtoMessage() {}

func (x *WireGuardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardConfig.ProtoReflect.Descriptor instead.
func (*WireGuardConfig) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *WireGuardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireGuardConfig) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *WireGuardConfig) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *WireGuardConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *WireGuardConfig) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *WireGuardConfig) GetReserved() []uint32 {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *WireGuardConfig) GetDomainStrategy() string {
	if x != nil {
		return x.DomainStrategy
	}
	return ""
}

type WireGuardPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Reserved      []uint32               `protobuf:"varint,4,rep,packed,name=reserved,proto3" json:"reserved,omitempty"`
	Keepalive     uint32                 `protobuf:"varint,5,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	PreSharedKey  string                 `protobuf:"bytes,6,opt,name=pre_shared_key,json=preSharedKey,proto3" json:"pre_shared_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	mi := &file_wireguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{1}
}

func (x *WireGuardPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WireGuardPeer) GetReserved() []uint32 {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *WireGuardPeer) GetKeepalive() uint32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

func (x *WireGuardPeer) GetPreSharedKey() string {
	if x != nil {
		return x.PreSharedKey
	}
	return ""
}

var File_wireguard_proto protoreflect.FileDescriptor

const file_wireguard_proto_rawDesc = "" +
	"\n" +
	"\x0fwireguard.proto\x12\n" +
	"proxyswarm\"\xf2\x01\n" +
	"\x0fWireGuardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12/\n" +
	"\x05peers\x18\x03 \x03(\v2\x19.proxyswarm.WireGuardPeerR\x05peers\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\x12\x18\n" +
	"\aworkers\x18\x05 \x01(\x05R\aworkers\x12\x1a\n" +
	"\breserved\x18\x06 \x03(\rR\breserved\x12'\n" +
	"\x0fdomain_strategy\x18\a \x01(\tR\x0edomainStrategy\"\xcb\x01\n" +
	"\rWireGuardPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12\x1a\n" +
	"\breserved\x18\x04 \x03(\rR\breserved\x12\x1c\n" +
	"\tkeepalive\x18\x05 \x01(\rR\tkeepalive\x12$\n" +
	"\x0epre_shared_key\x18\x06 \x01(\tR\fpreSharedKeyB\x06Z\x04./pbb\x06proto3"

var (
	file_wireguard_proto_rawDescOnce sync.Once
	file_wireguard_proto_rawDescData []byte
)

func file_wireguard_proto_rawDescGZIP() []byte {
	file_wireguard_proto_rawDescOnce.Do(func() {
		file_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wireguard_proto_rawDesc), len(file_wireguard_proto_rawDesc)))
	})
	return file_wireguard_proto_rawDescData
}

var file_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wireguard_proto_goTypes = []any{
	(*WireGuardConfig)(nil), // 0: proxyswarm.WireGuardConfig
	(*WireGuardPeer)(nil),   // 1: proxyswarm.WireGuardPeer
}
var file_wireguard_proto_depIdxs = []int32{
	1, // 0: proxyswarm.WireGuardConfig.peers:type_name -> proxyswarm.WireGuardPeer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wireguard_proto_init() }
func file_wireguard_proto_init() {
	if File_wireguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wireguard_proto_rawDesc), len(file_wireguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wireguard_proto_goTypes,
		DependencyIndexes: file_wireguard_proto_depIdxs,
		MessageInfos:      file_wireguard_proto_msgTypes,
	}.Build()
	File_wireguard_proto = out.File
	file_wireguard_proto_goTypes = nil
	file_wireguard_proto_depIdxs = nil
}
