// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/hysteria2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hysteria2Config struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Password              string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	ObfsType              string                 `protobuf:"bytes,2,opt,name=obfs_type,json=obfsType,proto3" json:"obfs_type,omitempty"`
	ObfsPassword          string                 `protobuf:"bytes,3,opt,name=obfs_password,json=obfsPassword,proto3" json:"obfs_password,omitempty"`
	UpMbps                uint32                 `protobuf:"varint,4,opt,name=up_mbps,json=upMbps,proto3" json:"up_mbps,omitempty"`
	DownMbps              uint32                 `protobuf:"varint,5,opt,name=down_mbps,json=downMbps,proto3" json:"down_mbps,omitempty"`
	Tls                   *TLSConfig             `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	IgnoreClientBandwidth bool                   `protobuf:"varint,7,opt,name=ignore_client_bandwidth,json=ignoreClientBandwidth,proto3" json:"ignore_client_bandwidth,omitempty"`
	Masquerade            string                 `protobuf:"bytes,8,opt,name=masquerade,proto3" json:"masquerade,omitempty"`
	BbrProfile            string                 `protobuf:"bytes,9,opt,name=bbr_profile,json=bbrProfile,proto3" json:"bbr_profile,omitempty"`
	BrutalDebug           bool                   `protobuf:"varint,10,opt,name=brutal_debug,json=brutalDebug,proto3" json:"brutal_debug,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Hysteria2Config) Reset() {
	*x = Hysteria2Config{}
	mi := &file_node_hysteria2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hysteria2Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hysteria2Config) ProtoMessage() {}

func (x *Hysteria2Config) ProtoReflect() protoreflect.Message {
	mi := &file_node_hysteria2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hysteria2Config.ProtoReflect.Descriptor instead.
func (*Hysteria2Config) Descriptor() ([]byte, []int) {
	return file_node_hysteria2_proto_rawDescGZIP(), []int{0}
}

func (x *Hysteria2Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Hysteria2Config) GetObfsType() string {
	if x != nil {
		return x.ObfsType
	}
	return ""
}

func (x *Hysteria2Config) GetObfsPassword() string {
	if x != nil {
		return x.ObfsPassword
	}
	return ""
}

func (x *Hysteria2Config) GetUpMbps() uint32 {
	if x != nil {
		return x.UpMbps
	}
	return 0
}

func (x *Hysteria2Config) GetDownMbps() uint32 {
	if x != nil {
		return x.DownMbps
	}
	return 0
}

func (x *Hysteria2Config) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Hysteria2Config) GetIgnoreClientBandwidth() bool {
	if x != nil {
		return x.IgnoreClientBandwidth
	}
	return false
}

func (x *Hysteria2Config) GetMasquerade() string {
	if x != nil {
		return x.Masquerade
	}
	return ""
}

func (x *Hysteria2Config) GetBbrProfile() string {
	if x != nil {
		return x.BbrProfile
	}
	return ""
}

func (x *Hysteria2Config) GetBrutalDebug() bool {
	if x != nil {
		return x.BrutalDebug
	}
	return false
}

var File_node_hysteria2_proto protoreflect.FileDescriptor

const file_node_hysteria2_proto_rawDesc = "" +
	"\n" +
	"\x14node/hysteria2.proto\x12\n" +
	"proxyswarm\x1a\x11node/common.proto\"\xea\x02\n" +
	"\x0fHysteria2Config\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1b\n" +
	"\tobfs_type\x18\x02 \x01(\tR\bobfsType\x12#\n" +
	"\robfs_password\x18\x03 \x01(\tR\fobfsPassword\x12\x17\n" +
	"\aup_mbps\x18\x04 \x01(\rR\x06upMbps\x12\x1b\n" +
	"\tdown_mbps\x18\x05 \x01(\rR\bdownMbps\x12'\n" +
	"\x03tls\x18\x06 \x01(\v2\x15.proxyswarm.TLSConfigR\x03tls\x126\n" +
	"\x17ignore_client_bandwidth\x18\a \x01(\bR\x15ignoreClientBandwidth\x12\x1e\n" +
	"\n" +
	"masquerade\x18\b \x01(\tR\n" +
	"masquerade\x12\x1f\n" +
	"\vbbr_profile\x18\t \x01(\tR\n" +
	"bbrProfile\x12!\n" +
	"\fbrutal_debug\x18\n" +
	" \x01(\bR\vbrutalDebugB\x06Z\x04./pbb\x06proto3"

var (
	file_node_hysteria2_proto_rawDescOnce sync.Once
	file_node_hysteria2_proto_rawDescData []byte
)

func file_node_hysteria2_proto_rawDescGZIP() []byte {
	file_node_hysteria2_proto_rawDescOnce.Do(func() {
		file_node_hysteria2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_hysteria2_proto_rawDesc), len(file_node_hysteria2_proto_rawDesc)))
	})
	return file_node_hysteria2_proto_rawDescData
}

var file_node_hysteria2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_hysteria2_proto_goTypes = []any{
	(*Hysteria2Config)(nil), // 0: proxyswarm.Hysteria2Config
	(*TLSConfig)(nil),       // 1: proxyswarm.TLSConfig
}
var file_node_hysteria2_proto_depIdxs = []int32{
	1, // 0: proxyswarm.Hysteria2Config.tls:type_name -> proxyswarm.TLSConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_hysteria2_proto_init() }
func file_node_hysteria2_proto_init() {
	if File_node_hysteria2_proto != nil {
		return
	}
	file_node_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_hysteria2_proto_rawDesc), len(file_node_hysteria2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_hysteria2_proto_goTypes,
		DependencyIndexes: file_node_hysteria2_proto_depIdxs,
		MessageInfos:      file_node_hysteria2_proto_msgTypes,
	}.Build()
	File_node_hysteria2_proto = out.File
	file_node_hysteria2_proto_goTypes = nil
	file_node_hysteria2_proto_depIdxs = nil
}
