// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: node/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_UpdateConfig_FullMethodName         = "/proxyswarm.NodeService/UpdateConfig"
	NodeService_GetStatus_FullMethodName            = "/proxyswarm.NodeService/GetStatus"
	NodeService_IssueAcmeCertificate_FullMethodName = "/proxyswarm.NodeService/IssueAcmeCertificate"
	NodeService_RegisterWarp_FullMethodName         = "/proxyswarm.NodeService/RegisterWarp"
	NodeService_UpdateWarpLicense_FullMethodName    = "/proxyswarm.NodeService/UpdateWarpLicense"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	UpdateConfig(ctx context.Context, in *FullConfig, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	IssueAcmeCertificate(ctx context.Context, in *AcmeIssueRequest, opts ...grpc.CallOption) (*AcmeIssueResponse, error)
	RegisterWarp(ctx context.Context, in *WarpRegisterRequest, opts ...grpc.CallOption) (*WarpRegisterResponse, error)
	UpdateWarpLicense(ctx context.Context, in *WarpLicenseUpdateRequest, opts ...grpc.CallOption) (*WarpLicenseUpdateResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) UpdateConfig(ctx context.Context, in *FullConfig, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, NodeService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) IssueAcmeCertificate(ctx context.Context, in *AcmeIssueRequest, opts ...grpc.CallOption) (*AcmeIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcmeIssueResponse)
	err := c.cc.Invoke(ctx, NodeService_IssueAcmeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RegisterWarp(ctx context.Context, in *WarpRegisterRequest, opts ...grpc.CallOption) (*WarpRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarpRegisterResponse)
	err := c.cc.Invoke(ctx, NodeService_RegisterWarp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateWarpLicense(ctx context.Context, in *WarpLicenseUpdateRequest, opts ...grpc.CallOption) (*WarpLicenseUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarpLicenseUpdateResponse)
	err := c.cc.Invoke(ctx, NodeService_UpdateWarpLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	UpdateConfig(context.Context, *FullConfig) (*UpdateResponse, error)
	GetStatus(context.Context, *StatusRequest) (*NodeStatus, error)
	IssueAcmeCertificate(context.Context, *AcmeIssueRequest) (*AcmeIssueResponse, error)
	RegisterWarp(context.Context, *WarpRegisterRequest) (*WarpRegisterResponse, error)
	UpdateWarpLicense(context.Context, *WarpLicenseUpdateRequest) (*WarpLicenseUpdateResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) UpdateConfig(context.Context, *FullConfig) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedNodeServiceServer) GetStatus(context.Context, *StatusRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodeServiceServer) IssueAcmeCertificate(context.Context, *AcmeIssueRequest) (*AcmeIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueAcmeCertificate not implemented")
}
func (UnimplementedNodeServiceServer) RegisterWarp(context.Context, *WarpRegisterRequest) (*WarpRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWarp not implemented")
}
func (UnimplementedNodeServiceServer) UpdateWarpLicense(context.Context, *WarpLicenseUpdateRequest) (*WarpLicenseUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWarpLicense not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateConfig(ctx, req.(*FullConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_IssueAcmeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).IssueAcmeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_IssueAcmeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).IssueAcmeCertificate(ctx, req.(*AcmeIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RegisterWarp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarpRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RegisterWarp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RegisterWarp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RegisterWarp(ctx, req.(*WarpRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateWarpLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarpLicenseUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateWarpLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateWarpLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateWarpLicense(ctx, req.(*WarpLicenseUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxyswarm.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConfig",
			Handler:    _NodeService_UpdateConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NodeService_GetStatus_Handler,
		},
		{
			MethodName: "IssueAcmeCertificate",
			Handler:    _NodeService_IssueAcmeCertificate_Handler,
		},
		{
			MethodName: "RegisterWarp",
			Handler:    _NodeService_RegisterWarp_Handler,
		},
		{
			MethodName: "UpdateWarpLicense",
			Handler:    _NodeService_UpdateWarpLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/service.proto",
}
