// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreType int32

const (
	CoreType_SING_BOX CoreType = 0
	CoreType_XRAY     CoreType = 1
)

// Enum value maps for CoreType.
var (
	CoreType_name = map[int32]string{
		0: "SING_BOX",
		1: "XRAY",
	}
	CoreType_value = map[string]int32{
		"SING_BOX": 0,
		"XRAY":     1,
	}
)

func (x CoreType) Enum() *CoreType {
	p := new(CoreType)
	*p = x
	return p
}

func (x CoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_service_proto_enumTypes[0].Descriptor()
}

func (CoreType) Type() protoreflect.EnumType {
	return &file_node_service_proto_enumTypes[0]
}

func (x CoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreType.Descriptor instead.
func (CoreType) EnumDescriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{0}
}

type OutboundType int32

const (
	OutboundType_DIRECT      OutboundType = 0
	OutboundType_BLOCK       OutboundType = 1
	OutboundType_VLESS       OutboundType = 2
	OutboundType_TRUSTTUNNEL OutboundType = 3
	OutboundType_WIREGUARD   OutboundType = 4
	OutboundType_SOCKS5      OutboundType = 5
	OutboundType_SHADOWSOCKS OutboundType = 6
)

// Enum value maps for OutboundType.
var (
	OutboundType_name = map[int32]string{
		0: "DIRECT",
		1: "BLOCK",
		2: "VLESS",
		3: "TRUSTTUNNEL",
		4: "WIREGUARD",
		5: "SOCKS5",
		6: "SHADOWSOCKS",
	}
	OutboundType_value = map[string]int32{
		"DIRECT":      0,
		"BLOCK":       1,
		"VLESS":       2,
		"TRUSTTUNNEL": 3,
		"WIREGUARD":   4,
		"SOCKS5":      5,
		"SHADOWSOCKS": 6,
	}
)

func (x OutboundType) Enum() *OutboundType {
	p := new(OutboundType)
	*p = x
	return p
}

func (x OutboundType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutboundType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_service_proto_enumTypes[1].Descriptor()
}

func (OutboundType) Type() protoreflect.EnumType {
	return &file_node_service_proto_enumTypes[1]
}

func (x OutboundType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutboundType.Descriptor instead.
func (OutboundType) EnumDescriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{1}
}

type FullConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	Inbounds      []*InboundConfig       `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Outbounds     []*OutboundConfig      `protobuf:"bytes,4,rep,name=outbounds,proto3" json:"outbounds,omitempty"`
	RoutingRules  []*RoutingRule         `protobuf:"bytes,5,rep,name=routing_rules,json=routingRules,proto3" json:"routing_rules,omitempty"`
	Certificates  []*CertificateConfig   `protobuf:"bytes,6,rep,name=certificates,proto3" json:"certificates,omitempty"`
	Dns           *DnsConfig             `protobuf:"bytes,7,opt,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullConfig) Reset() {
	*x = FullConfig{}
	mi := &file_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullConfig) ProtoMessage() {}

func (x *FullConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullConfig.ProtoReflect.Descriptor instead.
func (*FullConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *FullConfig) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *FullConfig) GetInbounds() []*InboundConfig {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *FullConfig) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *FullConfig) GetOutbounds() []*OutboundConfig {
	if x != nil {
		return x.Outbounds
	}
	return nil
}

func (x *FullConfig) GetRoutingRules() []*RoutingRule {
	if x != nil {
		return x.RoutingRules
	}
	return nil
}

func (x *FullConfig) GetCertificates() []*CertificateConfig {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *FullConfig) GetDns() *DnsConfig {
	if x != nil {
		return x.Dns
	}
	return nil
}

type InboundConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Listen   string                 `protobuf:"bytes,2,opt,name=listen,proto3" json:"listen,omitempty"` // e.g., "0.0.0.0"
	Port     int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Core     CoreType               `protobuf:"varint,5,opt,name=core,proto3,enum=proxyswarm.CoreType" json:"core,omitempty"`
	Accounts []*Account             `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Enabled  bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Types that are valid to be assigned to Protocol:
	//
	//	*InboundConfig_Vless
	//	*InboundConfig_Hysteria2
	//	*InboundConfig_Trusttunnel
	//	*InboundConfig_Naiveproxy
	//	*InboundConfig_Wireguard
	//	*InboundConfig_Socks5
	//	*InboundConfig_Shadowsocks
	Protocol      isInboundConfig_Protocol `protobuf_oneof:"protocol"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *InboundConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundConfig) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *InboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InboundConfig) GetCore() CoreType {
	if x != nil {
		return x.Core
	}
	return CoreType_SING_BOX
}

func (x *InboundConfig) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *InboundConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InboundConfig) GetProtocol() isInboundConfig_Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *InboundConfig) GetVless() *VlessConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Vless); ok {
			return x.Vless
		}
	}
	return nil
}

func (x *InboundConfig) GetHysteria2() *Hysteria2Config {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Hysteria2); ok {
			return x.Hysteria2
		}
	}
	return nil
}

func (x *InboundConfig) GetTrusttunnel() *TrustTunnelConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Trusttunnel); ok {
			return x.Trusttunnel
		}
	}
	return nil
}

func (x *InboundConfig) GetNaiveproxy() *NaiveProxyConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Naiveproxy); ok {
			return x.Naiveproxy
		}
	}
	return nil
}

func (x *InboundConfig) GetWireguard() *WireGuardConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Wireguard); ok {
			return x.Wireguard
		}
	}
	return nil
}

func (x *InboundConfig) GetSocks5() *Socks5InboundConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Socks5); ok {
			return x.Socks5
		}
	}
	return nil
}

func (x *InboundConfig) GetShadowsocks() *ShadowsocksInboundConfig {
	if x != nil {
		if x, ok := x.Protocol.(*InboundConfig_Shadowsocks); ok {
			return x.Shadowsocks
		}
	}
	return nil
}

type isInboundConfig_Protocol interface {
	isInboundConfig_Protocol()
}

type InboundConfig_Vless struct {
	Vless *VlessConfig `protobuf:"bytes,6,opt,name=vless,proto3,oneof"`
}

type InboundConfig_Hysteria2 struct {
	Hysteria2 *Hysteria2Config `protobuf:"bytes,7,opt,name=hysteria2,proto3,oneof"`
}

type InboundConfig_Trusttunnel struct {
	Trusttunnel *TrustTunnelConfig `protobuf:"bytes,8,opt,name=trusttunnel,proto3,oneof"`
}

type InboundConfig_Naiveproxy struct {
	Naiveproxy *NaiveProxyConfig `protobuf:"bytes,9,opt,name=naiveproxy,proto3,oneof"`
}

type InboundConfig_Wireguard struct {
	Wireguard *WireGuardConfig `protobuf:"bytes,10,opt,name=wireguard,proto3,oneof"`
}

type InboundConfig_Socks5 struct {
	Socks5 *Socks5InboundConfig `protobuf:"bytes,11,opt,name=socks5,proto3,oneof"`
}

type InboundConfig_Shadowsocks struct {
	Shadowsocks *ShadowsocksInboundConfig `protobuf:"bytes,13,opt,name=shadowsocks,proto3,oneof"`
}

func (*InboundConfig_Vless) isInboundConfig_Protocol() {}

func (*InboundConfig_Hysteria2) isInboundConfig_Protocol() {}

func (*InboundConfig_Trusttunnel) isInboundConfig_Protocol() {}

func (*InboundConfig_Naiveproxy) isInboundConfig_Protocol() {}

func (*InboundConfig_Wireguard) isInboundConfig_Protocol() {}

func (*InboundConfig_Socks5) isInboundConfig_Protocol() {}

func (*InboundConfig_Shadowsocks) isInboundConfig_Protocol() {}

type OutboundConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag   string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type  OutboundType           `protobuf:"varint,2,opt,name=type,proto3,enum=proxyswarm.OutboundType" json:"type,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*OutboundConfig_Vless
	//	*OutboundConfig_Trusttunnel
	//	*OutboundConfig_Wireguard
	//	*OutboundConfig_Socks5
	//	*OutboundConfig_Shadowsocks
	Settings      isOutboundConfig_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *OutboundConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundConfig) GetType() OutboundType {
	if x != nil {
		return x.Type
	}
	return OutboundType_DIRECT
}

func (x *OutboundConfig) GetSettings() isOutboundConfig_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *OutboundConfig) GetVless() *VlessOutboundConfig {
	if x != nil {
		if x, ok := x.Settings.(*OutboundConfig_Vless); ok {
			return x.Vless
		}
	}
	return nil
}

func (x *OutboundConfig) GetTrusttunnel() *TrustTunnelConfig {
	if x != nil {
		if x, ok := x.Settings.(*OutboundConfig_Trusttunnel); ok {
			return x.Trusttunnel
		}
	}
	return nil
}

func (x *OutboundConfig) GetWireguard() *WireGuardConfig {
	if x != nil {
		if x, ok := x.Settings.(*OutboundConfig_Wireguard); ok {
			return x.Wireguard
		}
	}
	return nil
}

func (x *OutboundConfig) GetSocks5() *Socks5OutboundConfig {
	if x != nil {
		if x, ok := x.Settings.(*OutboundConfig_Socks5); ok {
			return x.Socks5
		}
	}
	return nil
}

func (x *OutboundConfig) GetShadowsocks() *ShadowsocksOutboundConfig {
	if x != nil {
		if x, ok := x.Settings.(*OutboundConfig_Shadowsocks); ok {
			return x.Shadowsocks
		}
	}
	return nil
}

type isOutboundConfig_Settings interface {
	isOutboundConfig_Settings()
}

type OutboundConfig_Vless struct {
	Vless *VlessOutboundConfig `protobuf:"bytes,3,opt,name=vless,proto3,oneof"`
}

type OutboundConfig_Trusttunnel struct {
	Trusttunnel *TrustTunnelConfig `protobuf:"bytes,4,opt,name=trusttunnel,proto3,oneof"`
}

type OutboundConfig_Wireguard struct {
	Wireguard *WireGuardConfig `protobuf:"bytes,5,opt,name=wireguard,proto3,oneof"`
}

type OutboundConfig_Socks5 struct {
	Socks5 *Socks5OutboundConfig `protobuf:"bytes,6,opt,name=socks5,proto3,oneof"`
}

type OutboundConfig_Shadowsocks struct {
	Shadowsocks *ShadowsocksOutboundConfig `protobuf:"bytes,7,opt,name=shadowsocks,proto3,oneof"`
}

func (*OutboundConfig_Vless) isOutboundConfig_Settings() {}

func (*OutboundConfig_Trusttunnel) isOutboundConfig_Settings() {}

func (*OutboundConfig_Wireguard) isOutboundConfig_Settings() {}

func (*OutboundConfig_Socks5) isOutboundConfig_Settings() {}

func (*OutboundConfig_Shadowsocks) isOutboundConfig_Settings() {}

type VlessOutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Flow          string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	Security      SecurityMode           `protobuf:"varint,5,opt,name=security,proto3,enum=proxyswarm.SecurityMode" json:"security,omitempty"`
	Transmission  string                 `protobuf:"bytes,6,opt,name=transmission,proto3" json:"transmission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessOutboundConfig) Reset() {
	*x = VlessOutboundConfig{}
	mi := &file_node_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessOutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessOutboundConfig) ProtoMessage() {}

func (x *VlessOutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessOutboundConfig.ProtoReflect.Descriptor instead.
func (*VlessOutboundConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{3}
}

func (x *VlessOutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *VlessOutboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VlessOutboundConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VlessOutboundConfig) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *VlessOutboundConfig) GetSecurity() SecurityMode {
	if x != nil {
		return x.Security
	}
	return SecurityMode_NONE
}

func (x *VlessOutboundConfig) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

type RoutingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        []string               `protobuf:"bytes,1,rep,name=domain,proto3" json:"domain,omitempty"`
	Ip            []string               `protobuf:"bytes,2,rep,name=ip,proto3" json:"ip,omitempty"`
	Port          []string               `protobuf:"bytes,3,rep,name=port,proto3" json:"port,omitempty"`
	Transport     []string               `protobuf:"bytes,4,rep,name=transport,proto3" json:"transport,omitempty"`
	Protocol      []string               `protobuf:"bytes,5,rep,name=protocol,proto3" json:"protocol,omitempty"`
	OutboundTag   string                 `protobuf:"bytes,6,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	InboundTag    []string               `protobuf:"bytes,7,rep,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	User          []string               `protobuf:"bytes,8,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_node_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{4}
}

func (x *RoutingRule) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RoutingRule) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *RoutingRule) GetPort() []string {
	if x != nil {
		return x.Port
	}
	return nil
}

func (x *RoutingRule) GetTransport() []string {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *RoutingRule) GetProtocol() []string {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *RoutingRule) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RoutingRule) GetInboundTag() []string {
	if x != nil {
		return x.InboundTag
	}
	return nil
}

func (x *RoutingRule) GetUser() []string {
	if x != nil {
		return x.User
	}
	return nil
}

type DnsConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Servers                []*DnsServerConfig     `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Hosts                  []*DnsHostMapping      `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	ClientIp               string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Tag                    string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	QueryStrategy          string                 `protobuf:"bytes,5,opt,name=query_strategy,json=queryStrategy,proto3" json:"query_strategy,omitempty"`
	DisableCache           bool                   `protobuf:"varint,6,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	ServeStale             bool                   `protobuf:"varint,7,opt,name=serve_stale,json=serveStale,proto3" json:"serve_stale,omitempty"`
	ServeExpiredTtl        uint32                 `protobuf:"varint,8,opt,name=serve_expired_ttl,json=serveExpiredTtl,proto3" json:"serve_expired_ttl,omitempty"`
	DisableFallback        bool                   `protobuf:"varint,9,opt,name=disable_fallback,json=disableFallback,proto3" json:"disable_fallback,omitempty"`
	DisableFallbackIfMatch bool                   `protobuf:"varint,10,opt,name=disable_fallback_if_match,json=disableFallbackIfMatch,proto3" json:"disable_fallback_if_match,omitempty"`
	EnableParallelQuery    bool                   `protobuf:"varint,11,opt,name=enable_parallel_query,json=enableParallelQuery,proto3" json:"enable_parallel_query,omitempty"`
	UseSystemHosts         bool                   `protobuf:"varint,12,opt,name=use_system_hosts,json=useSystemHosts,proto3" json:"use_system_hosts,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DnsConfig) Reset() {
	*x = DnsConfig{}
	mi := &file_node_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsConfig) ProtoMessage() {}

func (x *DnsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsConfig.ProtoReflect.Descriptor instead.
func (*DnsConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{5}
}

func (x *DnsConfig) GetServers() []*DnsServerConfig {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *DnsConfig) GetHosts() []*DnsHostMapping {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *DnsConfig) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DnsConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DnsConfig) GetQueryStrategy() string {
	if x != nil {
		return x.QueryStrategy
	}
	return ""
}

func (x *DnsConfig) GetDisableCache() bool {
	if x != nil {
		return x.DisableCache
	}
	return false
}

func (x *DnsConfig) GetServeStale() bool {
	if x != nil {
		return x.ServeStale
	}
	return false
}

func (x *DnsConfig) GetServeExpiredTtl() uint32 {
	if x != nil {
		return x.ServeExpiredTtl
	}
	return 0
}

func (x *DnsConfig) GetDisableFallback() bool {
	if x != nil {
		return x.DisableFallback
	}
	return false
}

func (x *DnsConfig) GetDisableFallbackIfMatch() bool {
	if x != nil {
		return x.DisableFallbackIfMatch
	}
	return false
}

func (x *DnsConfig) GetEnableParallelQuery() bool {
	if x != nil {
		return x.EnableParallelQuery
	}
	return false
}

func (x *DnsConfig) GetUseSystemHosts() bool {
	if x != nil {
		return x.UseSystemHosts
	}
	return false
}

type DnsServerConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ClientIp        string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Port            uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	SkipFallback    bool                   `protobuf:"varint,4,opt,name=skip_fallback,json=skipFallback,proto3" json:"skip_fallback,omitempty"`
	Domains         []string               `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"`
	ExpectIps       []string               `protobuf:"bytes,6,rep,name=expect_ips,json=expectIps,proto3" json:"expect_ips,omitempty"`
	QueryStrategy   string                 `protobuf:"bytes,7,opt,name=query_strategy,json=queryStrategy,proto3" json:"query_strategy,omitempty"`
	Tag             string                 `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	TimeoutMs       uint64                 `protobuf:"varint,9,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	DisableCache    *bool                  `protobuf:"varint,10,opt,name=disable_cache,json=disableCache,proto3,oneof" json:"disable_cache,omitempty"`
	ServeStale      *bool                  `protobuf:"varint,11,opt,name=serve_stale,json=serveStale,proto3,oneof" json:"serve_stale,omitempty"`
	ServeExpiredTtl *uint32                `protobuf:"varint,12,opt,name=serve_expired_ttl,json=serveExpiredTtl,proto3,oneof" json:"serve_expired_ttl,omitempty"`
	FinalQuery      bool                   `protobuf:"varint,13,opt,name=final_query,json=finalQuery,proto3" json:"final_query,omitempty"`
	UnexpectedIps   []string               `protobuf:"bytes,14,rep,name=unexpected_ips,json=unexpectedIps,proto3" json:"unexpected_ips,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DnsServerConfig) Reset() {
	*x = DnsServerConfig{}
	mi := &file_node_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsServerConfig) ProtoMessage() {}

func (x *DnsServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsServerConfig.ProtoReflect.Descriptor instead.
func (*DnsServerConfig) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{6}
}

func (x *DnsServerConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DnsServerConfig) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DnsServerConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DnsServerConfig) GetSkipFallback() bool {
	if x != nil {
		return x.SkipFallback
	}
	return false
}

func (x *DnsServerConfig) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DnsServerConfig) GetExpectIps() []string {
	if x != nil {
		return x.ExpectIps
	}
	return nil
}

func (x *DnsServerConfig) GetQueryStrategy() string {
	if x != nil {
		return x.QueryStrategy
	}
	return ""
}

func (x *DnsServerConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DnsServerConfig) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DnsServerConfig) GetDisableCache() bool {
	if x != nil && x.DisableCache != nil {
		return *x.DisableCache
	}
	return false
}

func (x *DnsServerConfig) GetServeStale() bool {
	if x != nil && x.ServeStale != nil {
		return *x.ServeStale
	}
	return false
}

func (x *DnsServerConfig) GetServeExpiredTtl() uint32 {
	if x != nil && x.ServeExpiredTtl != nil {
		return *x.ServeExpiredTtl
	}
	return 0
}

func (x *DnsServerConfig) GetFinalQuery() bool {
	if x != nil {
		return x.FinalQuery
	}
	return false
}

func (x *DnsServerConfig) GetUnexpectedIps() []string {
	if x != nil {
		return x.UnexpectedIps
	}
	return nil
}

type DnsHostMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsHostMapping) Reset() {
	*x = DnsHostMapping{}
	mi := &file_node_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsHostMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsHostMapping) ProtoMessage() {}

func (x *DnsHostMapping) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsHostMapping.ProtoReflect.Descriptor instead.
func (*DnsHostMapping) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{7}
}

func (x *DnsHostMapping) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DnsHostMapping) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_node_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_node_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{9}
}

func (x *StatusRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

type AcmeIssueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MasterKey       string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	ChallengeType   string                 `protobuf:"bytes,4,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	Ca              string                 `protobuf:"bytes,5,opt,name=ca,proto3" json:"ca,omitempty"`
	Port            int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	CertificatePath string                 `protobuf:"bytes,7,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	KeyPath         string                 `protobuf:"bytes,8,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcmeIssueRequest) Reset() {
	*x = AcmeIssueRequest{}
	mi := &file_node_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeIssueRequest) ProtoMessage() {}

func (x *AcmeIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeIssueRequest.ProtoReflect.Descriptor instead.
func (*AcmeIssueRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{10}
}

func (x *AcmeIssueRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *AcmeIssueRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AcmeIssueRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AcmeIssueRequest) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *AcmeIssueRequest) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *AcmeIssueRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AcmeIssueRequest) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *AcmeIssueRequest) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

type AcmeIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Logs          []string               `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeIssueResponse) Reset() {
	*x = AcmeIssueResponse{}
	mi := &file_node_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeIssueResponse) ProtoMessage() {}

func (x *AcmeIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeIssueResponse.ProtoReflect.Descriptor instead.
func (*AcmeIssueResponse) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{11}
}

func (x *AcmeIssueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcmeIssueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AcmeIssueResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type WarpRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpRegisterRequest) Reset() {
	*x = WarpRegisterRequest{}
	mi := &file_node_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpRegisterRequest) ProtoMessage() {}

func (x *WarpRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpRegisterRequest.ProtoReflect.Descriptor instead.
func (*WarpRegisterRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{12}
}

func (x *WarpRegisterRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *WarpRegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type WarpRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	License       string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Reserved      []byte                 `protobuf:"bytes,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PeerPublicKey string                 `protobuf:"bytes,7,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpRegistration) Reset() {
	*x = WarpRegistration{}
	mi := &file_node_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpRegistration) ProtoMessage() {}

func (x *WarpRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpRegistration.ProtoReflect.Descriptor instead.
func (*WarpRegistration) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{13}
}

func (x *WarpRegistration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WarpRegistration) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WarpRegistration) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *WarpRegistration) GetReserved() []byte {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *WarpRegistration) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *WarpRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WarpRegistration) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

type WarpRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Registration  *WarpRegistration      `protobuf:"bytes,3,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpRegisterResponse) Reset() {
	*x = WarpRegisterResponse{}
	mi := &file_node_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpRegisterResponse) ProtoMessage() {}

func (x *WarpRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpRegisterResponse.ProtoReflect.Descriptor instead.
func (*WarpRegisterResponse) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{14}
}

func (x *WarpRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WarpRegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WarpRegisterResponse) GetRegistration() *WarpRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type WarpLicenseUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	License       string                 `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpLicenseUpdateRequest) Reset() {
	*x = WarpLicenseUpdateRequest{}
	mi := &file_node_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpLicenseUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpLicenseUpdateRequest) ProtoMessage() {}

func (x *WarpLicenseUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpLicenseUpdateRequest.ProtoReflect.Descriptor instead.
func (*WarpLicenseUpdateRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{15}
}

func (x *WarpLicenseUpdateRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *WarpLicenseUpdateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *WarpLicenseUpdateRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *WarpLicenseUpdateRequest) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

type WarpLicenseUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	License       string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpLicenseUpdateResponse) Reset() {
	*x = WarpLicenseUpdateResponse{}
	mi := &file_node_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpLicenseUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpLicenseUpdateResponse) ProtoMessage() {}

func (x *WarpLicenseUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpLicenseUpdateResponse.ProtoReflect.Descriptor instead.
func (*WarpLicenseUpdateResponse) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{16}
}

func (x *WarpLicenseUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WarpLicenseUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WarpLicenseUpdateResponse) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

var File_node_service_proto protoreflect.FileDescriptor

const file_node_service_proto_rawDesc = "" +
	"\n" +
	"\x12node/service.proto\x12\n" +
	"proxyswarm\x1a\raccount.proto\x1a\x11node/common.proto\x1a\x10node/vless.proto\x1a\x14node/hysteria2.proto\x1a\x16node/trusttunnel.proto\x1a\x15node/naiveproxy.proto\x1a\x14node/wireguard.proto\x1a\x11node/socks5.proto\x1a\x16node/shadowsocks.proto\"\xf7\x02\n" +
	"\n" +
	"FullConfig\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x125\n" +
	"\binbounds\x18\x02 \x03(\v2\x19.proxyswarm.InboundConfigR\binbounds\x12/\n" +
	"\baccounts\x18\x03 \x03(\v2\x13.proxyswarm.AccountR\baccounts\x128\n" +
	"\toutbounds\x18\x04 \x03(\v2\x1a.proxyswarm.OutboundConfigR\toutbounds\x12<\n" +
	"\rrouting_rules\x18\x05 \x03(\v2\x17.proxyswarm.RoutingRuleR\froutingRules\x12A\n" +
	"\fcertificates\x18\x06 \x03(\v2\x1d.proxyswarm.CertificateConfigR\fcertificates\x12'\n" +
	"\x03dns\x18\a \x01(\v2\x15.proxyswarm.DnsConfigR\x03dns\"\x83\x05\n" +
	"\rInboundConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06listen\x18\x02 \x01(\tR\x06listen\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12(\n" +
	"\x04core\x18\x05 \x01(\x0e2\x14.proxyswarm.CoreTypeR\x04core\x12/\n" +
	"\baccounts\x18\x04 \x03(\v2\x13.proxyswarm.AccountR\baccounts\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12/\n" +
	"\x05vless\x18\x06 \x01(\v2\x17.proxyswarm.VlessConfigH\x00R\x05vless\x12;\n" +
	"\thysteria2\x18\a \x01(\v2\x1b.proxyswarm.Hysteria2ConfigH\x00R\thysteria2\x12A\n" +
	"\vtrusttunnel\x18\b \x01(\v2\x1d.proxyswarm.TrustTunnelConfigH\x00R\vtrusttunnel\x12>\n" +
	"\n" +
	"naiveproxy\x18\t \x01(\v2\x1c.proxyswarm.NaiveProxyConfigH\x00R\n" +
	"naiveproxy\x12;\n" +
	"\twireguard\x18\n" +
	" \x01(\v2\x1b.proxyswarm.WireGuardConfigH\x00R\twireguard\x129\n" +
	"\x06socks5\x18\v \x01(\v2\x1f.proxyswarm.Socks5InboundConfigH\x00R\x06socks5\x12H\n" +
	"\vshadowsocks\x18\r \x01(\v2$.proxyswarm.ShadowsocksInboundConfigH\x00R\vshadowsocksB\n" +
	"\n" +
	"\bprotocol\"\x9c\x03\n" +
	"\x0eOutboundConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.proxyswarm.OutboundTypeR\x04type\x127\n" +
	"\x05vless\x18\x03 \x01(\v2\x1f.proxyswarm.VlessOutboundConfigH\x00R\x05vless\x12A\n" +
	"\vtrusttunnel\x18\x04 \x01(\v2\x1d.proxyswarm.TrustTunnelConfigH\x00R\vtrusttunnel\x12;\n" +
	"\twireguard\x18\x05 \x01(\v2\x1b.proxyswarm.WireGuardConfigH\x00R\twireguard\x12:\n" +
	"\x06socks5\x18\x06 \x01(\v2 .proxyswarm.Socks5OutboundConfigH\x00R\x06socks5\x12I\n" +
	"\vshadowsocks\x18\a \x01(\v2%.proxyswarm.ShadowsocksOutboundConfigH\x00R\vshadowsocksB\n" +
	"\n" +
	"\bsettings\"\xc3\x01\n" +
	"\x13VlessOutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\x124\n" +
	"\bsecurity\x18\x05 \x01(\x0e2\x18.proxyswarm.SecurityModeR\bsecurity\x12\"\n" +
	"\ftransmission\x18\x06 \x01(\tR\ftransmission\"\xdb\x01\n" +
	"\vRoutingRule\x12\x16\n" +
	"\x06domain\x18\x01 \x03(\tR\x06domain\x12\x0e\n" +
	"\x02ip\x18\x02 \x03(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x03(\tR\x04port\x12\x1c\n" +
	"\ttransport\x18\x04 \x03(\tR\ttransport\x12\x1a\n" +
	"\bprotocol\x18\x05 \x03(\tR\bprotocol\x12!\n" +
	"\foutbound_tag\x18\x06 \x01(\tR\voutboundTag\x12\x1f\n" +
	"\vinbound_tag\x18\a \x03(\tR\n" +
	"inboundTag\x12\x12\n" +
	"\x04user\x18\b \x03(\tR\x04user\"\x80\x04\n" +
	"\tDnsConfig\x125\n" +
	"\aservers\x18\x01 \x03(\v2\x1b.proxyswarm.DnsServerConfigR\aservers\x120\n" +
	"\x05hosts\x18\x02 \x03(\v2\x1a.proxyswarm.DnsHostMappingR\x05hosts\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12%\n" +
	"\x0equery_strategy\x18\x05 \x01(\tR\rqueryStrategy\x12#\n" +
	"\rdisable_cache\x18\x06 \x01(\bR\fdisableCache\x12\x1f\n" +
	"\vserve_stale\x18\a \x01(\bR\n" +
	"serveStale\x12*\n" +
	"\x11serve_expired_ttl\x18\b \x01(\rR\x0fserveExpiredTtl\x12)\n" +
	"\x10disable_fallback\x18\t \x01(\bR\x0fdisableFallback\x129\n" +
	"\x19disable_fallback_if_match\x18\n" +
	" \x01(\bR\x16disableFallbackIfMatch\x122\n" +
	"\x15enable_parallel_query\x18\v \x01(\bR\x13enableParallelQuery\x12(\n" +
	"\x10use_system_hosts\x18\f \x01(\bR\x0euseSystemHosts\"\x93\x04\n" +
	"\x0fDnsServerConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12#\n" +
	"\rskip_fallback\x18\x04 \x01(\bR\fskipFallback\x12\x18\n" +
	"\adomains\x18\x05 \x03(\tR\adomains\x12\x1d\n" +
	"\n" +
	"expect_ips\x18\x06 \x03(\tR\texpectIps\x12%\n" +
	"\x0equery_strategy\x18\a \x01(\tR\rqueryStrategy\x12\x10\n" +
	"\x03tag\x18\b \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\t \x01(\x04R\ttimeoutMs\x12(\n" +
	"\rdisable_cache\x18\n" +
	" \x01(\bH\x00R\fdisableCache\x88\x01\x01\x12$\n" +
	"\vserve_stale\x18\v \x01(\bH\x01R\n" +
	"serveStale\x88\x01\x01\x12/\n" +
	"\x11serve_expired_ttl\x18\f \x01(\rH\x02R\x0fserveExpiredTtl\x88\x01\x01\x12\x1f\n" +
	"\vfinal_query\x18\r \x01(\bR\n" +
	"finalQuery\x12%\n" +
	"\x0eunexpected_ips\x18\x0e \x03(\tR\runexpectedIpsB\x10\n" +
	"\x0e_disable_cacheB\x0e\n" +
	"\f_serve_staleB\x14\n" +
	"\x12_serve_expired_ttl\"@\n" +
	"\x0eDnsHostMapping\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"@\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\"\xf0\x01\n" +
	"\x10AcmeIssueRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12%\n" +
	"\x0echallenge_type\x18\x04 \x01(\tR\rchallengeType\x12\x0e\n" +
	"\x02ca\x18\x05 \x01(\tR\x02ca\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12)\n" +
	"\x10certificate_path\x18\a \x01(\tR\x0fcertificatePath\x12\x19\n" +
	"\bkey_path\x18\b \x01(\tR\akeyPath\"W\n" +
	"\x11AcmeIssueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04logs\x18\x03 \x03(\tR\x04logs\"S\n" +
	"\x13WarpRegisterRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\xd0\x01\n" +
	"\x10WarpRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\fR\breserved\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12&\n" +
	"\x0fpeer_public_key\x18\a \x01(\tR\rpeerPublicKey\"\x88\x01\n" +
	"\x14WarpRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12@\n" +
	"\fregistration\x18\x03 \x01(\v2\x1c.proxyswarm.WarpRegistrationR\fregistration\"\x93\x01\n" +
	"\x18WarpLicenseUpdateRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12\x18\n" +
	"\alicense\x18\x04 \x01(\tR\alicense\"e\n" +
	"\x19WarpLicenseUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense*\"\n" +
	"\bCoreType\x12\f\n" +
	"\bSING_BOX\x10\x00\x12\b\n" +
	"\x04XRAY\x10\x01*m\n" +
	"\fOutboundType\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\x12\t\n" +
	"\x05VLESS\x10\x02\x12\x0f\n" +
	"\vTRUSTTUNNEL\x10\x03\x12\r\n" +
	"\tWIREGUARD\x10\x04\x12\n" +
	"\n" +
	"\x06SOCKS5\x10\x05\x12\x0f\n" +
	"\vSHADOWSOCKS\x10\x062\x9b\x03\n" +
	"\vNodeService\x12B\n" +
	"\fUpdateConfig\x12\x16.proxyswarm.FullConfig\x1a\x1a.proxyswarm.UpdateResponse\x12>\n" +
	"\tGetStatus\x12\x19.proxyswarm.StatusRequest\x1a\x16.proxyswarm.NodeStatus\x12S\n" +
	"\x14IssueAcmeCertificate\x12\x1c.proxyswarm.AcmeIssueRequest\x1a\x1d.proxyswarm.AcmeIssueResponse\x12Q\n" +
	"\fRegisterWarp\x12\x1f.proxyswarm.WarpRegisterRequest\x1a .proxyswarm.WarpRegisterResponse\x12`\n" +
	"\x11UpdateWarpLicense\x12$.proxyswarm.WarpLicenseUpdateRequest\x1a%.proxyswarm.WarpLicenseUpdateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_node_service_proto_rawDescOnce sync.Once
	file_node_service_proto_rawDescData []byte
)

func file_node_service_proto_rawDescGZIP() []byte {
	file_node_service_proto_rawDescOnce.Do(func() {
		file_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_service_proto_rawDesc), len(file_node_service_proto_rawDesc)))
	})
	return file_node_service_proto_rawDescData
}

var file_node_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_node_service_proto_goTypes = []any{
	(CoreType)(0),                     // 0: proxyswarm.CoreType
	(OutboundType)(0),                 // 1: proxyswarm.OutboundType
	(*FullConfig)(nil),                // 2: proxyswarm.FullConfig
	(*InboundConfig)(nil),             // 3: proxyswarm.InboundConfig
	(*OutboundConfig)(nil),            // 4: proxyswarm.OutboundConfig
	(*VlessOutboundConfig)(nil),       // 5: proxyswarm.VlessOutboundConfig
	(*RoutingRule)(nil),               // 6: proxyswarm.RoutingRule
	(*DnsConfig)(nil),                 // 7: proxyswarm.DnsConfig
	(*DnsServerConfig)(nil),           // 8: proxyswarm.DnsServerConfig
	(*DnsHostMapping)(nil),            // 9: proxyswarm.DnsHostMapping
	(*UpdateResponse)(nil),            // 10: proxyswarm.UpdateResponse
	(*StatusRequest)(nil),             // 11: proxyswarm.StatusRequest
	(*AcmeIssueRequest)(nil),          // 12: proxyswarm.AcmeIssueRequest
	(*AcmeIssueResponse)(nil),         // 13: proxyswarm.AcmeIssueResponse
	(*WarpRegisterRequest)(nil),       // 14: proxyswarm.WarpRegisterRequest
	(*WarpRegistration)(nil),          // 15: proxyswarm.WarpRegistration
	(*WarpRegisterResponse)(nil),      // 16: proxyswarm.WarpRegisterResponse
	(*WarpLicenseUpdateRequest)(nil),  // 17: proxyswarm.WarpLicenseUpdateRequest
	(*WarpLicenseUpdateResponse)(nil), // 18: proxyswarm.WarpLicenseUpdateResponse
	(*Account)(nil),                   // 19: proxyswarm.Account
	(*CertificateConfig)(nil),         // 20: proxyswarm.CertificateConfig
	(*VlessConfig)(nil),               // 21: proxyswarm.VlessConfig
	(*Hysteria2Config)(nil),           // 22: proxyswarm.Hysteria2Config
	(*TrustTunnelConfig)(nil),         // 23: proxyswarm.TrustTunnelConfig
	(*NaiveProxyConfig)(nil),          // 24: proxyswarm.NaiveProxyConfig
	(*WireGuardConfig)(nil),           // 25: proxyswarm.WireGuardConfig
	(*Socks5InboundConfig)(nil),       // 26: proxyswarm.Socks5InboundConfig
	(*ShadowsocksInboundConfig)(nil),  // 27: proxyswarm.ShadowsocksInboundConfig
	(*Socks5OutboundConfig)(nil),      // 28: proxyswarm.Socks5OutboundConfig
	(*ShadowsocksOutboundConfig)(nil), // 29: proxyswarm.ShadowsocksOutboundConfig
	(SecurityMode)(0),                 // 30: proxyswarm.SecurityMode
	(*NodeStatus)(nil),                // 31: proxyswarm.NodeStatus
}
var file_node_service_proto_depIdxs = []int32{
	3,  // 0: proxyswarm.FullConfig.inbounds:type_name -> proxyswarm.InboundConfig
	19, // 1: proxyswarm.FullConfig.accounts:type_name -> proxyswarm.Account
	4,  // 2: proxyswarm.FullConfig.outbounds:type_name -> proxyswarm.OutboundConfig
	6,  // 3: proxyswarm.FullConfig.routing_rules:type_name -> proxyswarm.RoutingRule
	20, // 4: proxyswarm.FullConfig.certificates:type_name -> proxyswarm.CertificateConfig
	7,  // 5: proxyswarm.FullConfig.dns:type_name -> proxyswarm.DnsConfig
	0,  // 6: proxyswarm.InboundConfig.core:type_name -> proxyswarm.CoreType
	19, // 7: proxyswarm.InboundConfig.accounts:type_name -> proxyswarm.Account
	21, // 8: proxyswarm.InboundConfig.vless:type_name -> proxyswarm.VlessConfig
	22, // 9: proxyswarm.InboundConfig.hysteria2:type_name -> proxyswarm.Hysteria2Config
	23, // 10: proxyswarm.InboundConfig.trusttunnel:type_name -> proxyswarm.TrustTunnelConfig
	24, // 11: proxyswarm.InboundConfig.naiveproxy:type_name -> proxyswarm.NaiveProxyConfig
	25, // 12: proxyswarm.InboundConfig.wireguard:type_name -> proxyswarm.WireGuardConfig
	26, // 13: proxyswarm.InboundConfig.socks5:type_name -> proxyswarm.Socks5InboundConfig
	27, // 14: proxyswarm.InboundConfig.shadowsocks:type_name -> proxyswarm.ShadowsocksInboundConfig
	1,  // 15: proxyswarm.OutboundConfig.type:type_name -> proxyswarm.OutboundType
	5,  // 16: proxyswarm.OutboundConfig.vless:type_name -> proxyswarm.VlessOutboundConfig
	23, // 17: proxyswarm.OutboundConfig.trusttunnel:type_name -> proxyswarm.TrustTunnelConfig
	25, // 18: proxyswarm.OutboundConfig.wireguard:type_name -> proxyswarm.WireGuardConfig
	28, // 19: proxyswarm.OutboundConfig.socks5:type_name -> proxyswarm.Socks5OutboundConfig
	29, // 20: proxyswarm.OutboundConfig.shadowsocks:type_name -> proxyswarm.ShadowsocksOutboundConfig
	30, // 21: proxyswarm.VlessOutboundConfig.security:type_name -> proxyswarm.SecurityMode
	8,  // 22: proxyswarm.DnsConfig.servers:type_name -> proxyswarm.DnsServerConfig
	9,  // 23: proxyswarm.DnsConfig.hosts:type_name -> proxyswarm.DnsHostMapping
	15, // 24: proxyswarm.WarpRegisterResponse.registration:type_name -> proxyswarm.WarpRegistration
	2,  // 25: proxyswarm.NodeService.UpdateConfig:input_type -> proxyswarm.FullConfig
	11, // 26: proxyswarm.NodeService.GetStatus:input_type -> proxyswarm.StatusRequest
	12, // 27: proxyswarm.NodeService.IssueAcmeCertificate:input_type -> proxyswarm.AcmeIssueRequest
	14, // 28: proxyswarm.NodeService.RegisterWarp:input_type -> proxyswarm.WarpRegisterRequest
	17, // 29: proxyswarm.NodeService.UpdateWarpLicense:input_type -> proxyswarm.WarpLicenseUpdateRequest
	10, // 30: proxyswarm.NodeService.UpdateConfig:output_type -> proxyswarm.UpdateResponse
	31, // 31: proxyswarm.NodeService.GetStatus:output_type -> proxyswarm.NodeStatus
	13, // 32: proxyswarm.NodeService.IssueAcmeCertificate:output_type -> proxyswarm.AcmeIssueResponse
	16, // 33: proxyswarm.NodeService.RegisterWarp:output_type -> proxyswarm.WarpRegisterResponse
	18, // 34: proxyswarm.NodeService.UpdateWarpLicense:output_type -> proxyswarm.WarpLicenseUpdateResponse
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_node_service_proto_init() }
func file_node_service_proto_init() {
	if File_node_service_proto != nil {
		return
	}
	file_account_proto_init()
	file_node_common_proto_init()
	file_node_vless_proto_init()
	file_node_hysteria2_proto_init()
	file_node_trusttunnel_proto_init()
	file_node_naiveproxy_proto_init()
	file_node_wireguard_proto_init()
	file_node_socks5_proto_init()
	file_node_shadowsocks_proto_init()
	file_node_service_proto_msgTypes[1].OneofWrappers = []any{
		(*InboundConfig_Vless)(nil),
		(*InboundConfig_Hysteria2)(nil),
		(*InboundConfig_Trusttunnel)(nil),
		(*InboundConfig_Naiveproxy)(nil),
		(*InboundConfig_Wireguard)(nil),
		(*InboundConfig_Socks5)(nil),
		(*InboundConfig_Shadowsocks)(nil),
	}
	file_node_service_proto_msgTypes[2].OneofWrappers = []any{
		(*OutboundConfig_Vless)(nil),
		(*OutboundConfig_Trusttunnel)(nil),
		(*OutboundConfig_Wireguard)(nil),
		(*OutboundConfig_Socks5)(nil),
		(*OutboundConfig_Shadowsocks)(nil),
	}
	file_node_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_service_proto_rawDesc), len(file_node_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_service_proto_goTypes,
		DependencyIndexes: file_node_service_proto_depIdxs,
		EnumInfos:         file_node_service_proto_enumTypes,
		MessageInfos:      file_node_service_proto_msgTypes,
	}.Build()
	File_node_service_proto = out.File
	file_node_service_proto_goTypes = nil
	file_node_service_proto_depIdxs = nil
}
