// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/shadowsocks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShadowsocksInboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UdpEnabled    bool                   `protobuf:"varint,3,opt,name=udp_enabled,json=udpEnabled,proto3" json:"udp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowsocksInboundConfig) Reset() {
	*x = ShadowsocksInboundConfig{}
	mi := &file_node_shadowsocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowsocksInboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksInboundConfig) ProtoMessage() {}

func (x *ShadowsocksInboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_shadowsocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksInboundConfig.ProtoReflect.Descriptor instead.
func (*ShadowsocksInboundConfig) Descriptor() ([]byte, []int) {
	return file_node_shadowsocks_proto_rawDescGZIP(), []int{0}
}

func (x *ShadowsocksInboundConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ShadowsocksInboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksInboundConfig) GetUdpEnabled() bool {
	if x != nil {
		return x.UdpEnabled
	}
	return false
}

type ShadowsocksOutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Plugin        string                 `protobuf:"bytes,5,opt,name=plugin,proto3" json:"plugin,omitempty"`
	PluginOpts    string                 `protobuf:"bytes,6,opt,name=plugin_opts,json=pluginOpts,proto3" json:"plugin_opts,omitempty"`
	Prefix        string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	UdpEnabled    bool                   `protobuf:"varint,8,opt,name=udp_enabled,json=udpEnabled,proto3" json:"udp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowsocksOutboundConfig) Reset() {
	*x = ShadowsocksOutboundConfig{}
	mi := &file_node_shadowsocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowsocksOutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksOutboundConfig) ProtoMessage() {}

func (x *ShadowsocksOutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_shadowsocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksOutboundConfig.ProtoReflect.Descriptor instead.
func (*ShadowsocksOutboundConfig) Descriptor() ([]byte, []int) {
	return file_node_shadowsocks_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowsocksOutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShadowsocksOutboundConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetPluginOpts() string {
	if x != nil {
		return x.PluginOpts
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ShadowsocksOutboundConfig) GetUdpEnabled() bool {
	if x != nil {
		return x.UdpEnabled
	}
	return false
}

var File_node_shadowsocks_proto protoreflect.FileDescriptor

const file_node_shadowsocks_proto_rawDesc = "" +
	"\n" +
	"\x16node/shadowsocks.proto\x12\n" +
	"proxyswarm\"o\n" +
	"\x18ShadowsocksInboundConfig\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vudp_enabled\x18\x03 \x01(\bR\n" +
	"udpEnabled\"\xed\x01\n" +
	"\x19ShadowsocksOutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x16\n" +
	"\x06plugin\x18\x05 \x01(\tR\x06plugin\x12\x1f\n" +
	"\vplugin_opts\x18\x06 \x01(\tR\n" +
	"pluginOpts\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12\x1f\n" +
	"\vudp_enabled\x18\b \x01(\bR\n" +
	"udpEnabledB\x06Z\x04./pbb\x06proto3"

var (
	file_node_shadowsocks_proto_rawDescOnce sync.Once
	file_node_shadowsocks_proto_rawDescData []byte
)

func file_node_shadowsocks_proto_rawDescGZIP() []byte {
	file_node_shadowsocks_proto_rawDescOnce.Do(func() {
		file_node_shadowsocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_shadowsocks_proto_rawDesc), len(file_node_shadowsocks_proto_rawDesc)))
	})
	return file_node_shadowsocks_proto_rawDescData
}

var file_node_shadowsocks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_shadowsocks_proto_goTypes = []any{
	(*ShadowsocksInboundConfig)(nil),  // 0: proxyswarm.ShadowsocksInboundConfig
	(*ShadowsocksOutboundConfig)(nil), // 1: proxyswarm.ShadowsocksOutboundConfig
}
var file_node_shadowsocks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_shadowsocks_proto_init() }
func file_node_shadowsocks_proto_init() {
	if File_node_shadowsocks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_shadowsocks_proto_rawDesc), len(file_node_shadowsocks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_shadowsocks_proto_goTypes,
		DependencyIndexes: file_node_shadowsocks_proto_depIdxs,
		MessageInfos:      file_node_shadowsocks_proto_msgTypes,
	}.Build()
	File_node_shadowsocks_proto = out.File
	file_node_shadowsocks_proto_goTypes = nil
	file_node_shadowsocks_proto_depIdxs = nil
}
