// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/trusttunnel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrustTunnelConfig struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Http1UploadBufferSize            uint32                 `protobuf:"varint,1,opt,name=http1_upload_buffer_size,json=http1UploadBufferSize,proto3" json:"http1_upload_buffer_size,omitempty"`
	Http2InitialConnectionWindowSize uint32                 `protobuf:"varint,2,opt,name=http2_initial_connection_window_size,json=http2InitialConnectionWindowSize,proto3" json:"http2_initial_connection_window_size,omitempty"`
	Http2InitialStreamWindowSize     uint32                 `protobuf:"varint,3,opt,name=http2_initial_stream_window_size,json=http2InitialStreamWindowSize,proto3" json:"http2_initial_stream_window_size,omitempty"`
	Http2MaxConcurrentStreams        uint32                 `protobuf:"varint,4,opt,name=http2_max_concurrent_streams,json=http2MaxConcurrentStreams,proto3" json:"http2_max_concurrent_streams,omitempty"`
	Http2MaxFrameSize                uint32                 `protobuf:"varint,5,opt,name=http2_max_frame_size,json=http2MaxFrameSize,proto3" json:"http2_max_frame_size,omitempty"`
	Http2HeaderTableSize             uint32                 `protobuf:"varint,6,opt,name=http2_header_table_size,json=http2HeaderTableSize,proto3" json:"http2_header_table_size,omitempty"`
	Tls                              *TLSConfig             `protobuf:"bytes,7,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *TrustTunnelConfig) Reset() {
	*x = TrustTunnelConfig{}
	mi := &file_node_trusttunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustTunnelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustTunnelConfig) ProtoMessage() {}

func (x *TrustTunnelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_trusttunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustTunnelConfig.ProtoReflect.Descriptor instead.
func (*TrustTunnelConfig) Descriptor() ([]byte, []int) {
	return file_node_trusttunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TrustTunnelConfig) GetHttp1UploadBufferSize() uint32 {
	if x != nil {
		return x.Http1UploadBufferSize
	}
	return 0
}

func (x *TrustTunnelConfig) GetHttp2InitialConnectionWindowSize() uint32 {
	if x != nil {
		return x.Http2InitialConnectionWindowSize
	}
	return 0
}

func (x *TrustTunnelConfig) GetHttp2InitialStreamWindowSize() uint32 {
	if x != nil {
		return x.Http2InitialStreamWindowSize
	}
	return 0
}

func (x *TrustTunnelConfig) GetHttp2MaxConcurrentStreams() uint32 {
	if x != nil {
		return x.Http2MaxConcurrentStreams
	}
	return 0
}

func (x *TrustTunnelConfig) GetHttp2MaxFrameSize() uint32 {
	if x != nil {
		return x.Http2MaxFrameSize
	}
	return 0
}

func (x *TrustTunnelConfig) GetHttp2HeaderTableSize() uint32 {
	if x != nil {
		return x.Http2HeaderTableSize
	}
	return 0
}

func (x *TrustTunnelConfig) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_node_trusttunnel_proto protoreflect.FileDescriptor

const file_node_trusttunnel_proto_rawDesc = "" +
	"\n" +
	"\x16node/trusttunnel.proto\x12\n" +
	"proxyswarm\x1a\x11node/common.proto\"\xb6\x03\n" +
	"\x11TrustTunnelConfig\x127\n" +
	"\x18http1_upload_buffer_size\x18\x01 \x01(\rR\x15http1UploadBufferSize\x12N\n" +
	"$http2_initial_connection_window_size\x18\x02 \x01(\rR http2InitialConnectionWindowSize\x12F\n" +
	" http2_initial_stream_window_size\x18\x03 \x01(\rR\x1chttp2InitialStreamWindowSize\x12?\n" +
	"\x1chttp2_max_concurrent_streams\x18\x04 \x01(\rR\x19http2MaxConcurrentStreams\x12/\n" +
	"\x14http2_max_frame_size\x18\x05 \x01(\rR\x11http2MaxFrameSize\x125\n" +
	"\x17http2_header_table_size\x18\x06 \x01(\rR\x14http2HeaderTableSize\x12'\n" +
	"\x03tls\x18\a \x01(\v2\x15.proxyswarm.TLSConfigR\x03tlsB\x06Z\x04./pbb\x06proto3"

var (
	file_node_trusttunnel_proto_rawDescOnce sync.Once
	file_node_trusttunnel_proto_rawDescData []byte
)

func file_node_trusttunnel_proto_rawDescGZIP() []byte {
	file_node_trusttunnel_proto_rawDescOnce.Do(func() {
		file_node_trusttunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_trusttunnel_proto_rawDesc), len(file_node_trusttunnel_proto_rawDesc)))
	})
	return file_node_trusttunnel_proto_rawDescData
}

var file_node_trusttunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_trusttunnel_proto_goTypes = []any{
	(*TrustTunnelConfig)(nil), // 0: proxyswarm.TrustTunnelConfig
	(*TLSConfig)(nil),         // 1: proxyswarm.TLSConfig
}
var file_node_trusttunnel_proto_depIdxs = []int32{
	1, // 0: proxyswarm.TrustTunnelConfig.tls:type_name -> proxyswarm.TLSConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_trusttunnel_proto_init() }
func file_node_trusttunnel_proto_init() {
	if File_node_trusttunnel_proto != nil {
		return
	}
	file_node_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_trusttunnel_proto_rawDesc), len(file_node_trusttunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_trusttunnel_proto_goTypes,
		DependencyIndexes: file_node_trusttunnel_proto_depIdxs,
		MessageInfos:      file_node_trusttunnel_proto_msgTypes,
	}.Build()
	File_node_trusttunnel_proto = out.File
	file_node_trusttunnel_proto_goTypes = nil
	file_node_trusttunnel_proto_depIdxs = nil
}
