// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node/vless.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityMode int32

const (
	SecurityMode_NONE    SecurityMode = 0
	SecurityMode_TLS     SecurityMode = 1
	SecurityMode_REALITY SecurityMode = 2
)

// Enum value maps for SecurityMode.
var (
	SecurityMode_name = map[int32]string{
		0: "NONE",
		1: "TLS",
		2: "REALITY",
	}
	SecurityMode_value = map[string]int32{
		"NONE":    0,
		"TLS":     1,
		"REALITY": 2,
	}
)

func (x SecurityMode) Enum() *SecurityMode {
	p := new(SecurityMode)
	*p = x
	return p
}

func (x SecurityMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityMode) Descriptor() protoreflect.EnumDescriptor {
	return file_node_vless_proto_enumTypes[0].Descriptor()
}

func (SecurityMode) Type() protoreflect.EnumType {
	return &file_node_vless_proto_enumTypes[0]
}

func (x SecurityMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityMode.Descriptor instead.
func (SecurityMode) EnumDescriptor() ([]byte, []int) {
	return file_node_vless_proto_rawDescGZIP(), []int{0}
}

type VlessRealityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dest          string                 `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ShortId       []string               `protobuf:"bytes,3,rep,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Sni           string                 `protobuf:"bytes,5,opt,name=sni,proto3" json:"sni,omitempty"`
	Utls          string                 `protobuf:"bytes,6,opt,name=utls,proto3" json:"utls,omitempty"`
	SpiderX       string                 `protobuf:"bytes,7,opt,name=spider_x,json=spiderX,proto3" json:"spider_x,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessRealityConfig) Reset() {
	*x = VlessRealityConfig{}
	mi := &file_node_vless_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessRealityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessRealityConfig) ProtoMessage() {}

func (x *VlessRealityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_vless_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessRealityConfig.ProtoReflect.Descriptor instead.
func (*VlessRealityConfig) Descriptor() ([]byte, []int) {
	return file_node_vless_proto_rawDescGZIP(), []int{0}
}

func (x *VlessRealityConfig) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *VlessRealityConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *VlessRealityConfig) GetShortId() []string {
	if x != nil {
		return x.ShortId
	}
	return nil
}

func (x *VlessRealityConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VlessRealityConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *VlessRealityConfig) GetUtls() string {
	if x != nil {
		return x.Utls
	}
	return ""
}

func (x *VlessRealityConfig) GetSpiderX() string {
	if x != nil {
		return x.SpiderX
	}
	return ""
}

type VlessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	Security      SecurityMode           `protobuf:"varint,3,opt,name=security,proto3,enum=proxyswarm.SecurityMode" json:"security,omitempty"`
	Transmission  string                 `protobuf:"bytes,4,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	Reality       *VlessRealityConfig    `protobuf:"bytes,6,opt,name=reality,proto3" json:"reality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessConfig) Reset() {
	*x = VlessConfig{}
	mi := &file_node_vless_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessConfig) ProtoMessage() {}

func (x *VlessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_vless_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessConfig.ProtoReflect.Descriptor instead.
func (*VlessConfig) Descriptor() ([]byte, []int) {
	return file_node_vless_proto_rawDescGZIP(), []int{1}
}

func (x *VlessConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VlessConfig) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *VlessConfig) GetSecurity() SecurityMode {
	if x != nil {
		return x.Security
	}
	return SecurityMode_NONE
}

func (x *VlessConfig) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *VlessConfig) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *VlessConfig) GetReality() *VlessRealityConfig {
	if x != nil {
		return x.Reality
	}
	return nil
}

var File_node_vless_proto protoreflect.FileDescriptor

const file_node_vless_proto_rawDesc = "" +
	"\n" +
	"\x10node/vless.proto\x12\n" +
	"proxyswarm\x1a\x11node/common.proto\"\xc4\x01\n" +
	"\x12VlessRealityConfig\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12\x19\n" +
	"\bshort_id\x18\x03 \x03(\tR\ashortId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x10\n" +
	"\x03sni\x18\x05 \x01(\tR\x03sni\x12\x12\n" +
	"\x04utls\x18\x06 \x01(\tR\x04utls\x12\x19\n" +
	"\bspider_x\x18\a \x01(\tR\aspiderX\"\xf2\x01\n" +
	"\vVlessConfig\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\x124\n" +
	"\bsecurity\x18\x03 \x01(\x0e2\x18.proxyswarm.SecurityModeR\bsecurity\x12\"\n" +
	"\ftransmission\x18\x04 \x01(\tR\ftransmission\x12'\n" +
	"\x03tls\x18\x05 \x01(\v2\x15.proxyswarm.TLSConfigR\x03tls\x128\n" +
	"\areality\x18\x06 \x01(\v2\x1e.proxyswarm.VlessRealityConfigR\areality*.\n" +
	"\fSecurityMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03TLS\x10\x01\x12\v\n" +
	"\aREALITY\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_node_vless_proto_rawDescOnce sync.Once
	file_node_vless_proto_rawDescData []byte
)

func file_node_vless_proto_rawDescGZIP() []byte {
	file_node_vless_proto_rawDescOnce.Do(func() {
		file_node_vless_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_vless_proto_rawDesc), len(file_node_vless_proto_rawDesc)))
	})
	return file_node_vless_proto_rawDescData
}

var file_node_vless_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_vless_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_vless_proto_goTypes = []any{
	(SecurityMode)(0),          // 0: proxyswarm.SecurityMode
	(*VlessRealityConfig)(nil), // 1: proxyswarm.VlessRealityConfig
	(*VlessConfig)(nil),        // 2: proxyswarm.VlessConfig
	(*TLSConfig)(nil),          // 3: proxyswarm.TLSConfig
}
var file_node_vless_proto_depIdxs = []int32{
	0, // 0: proxyswarm.VlessConfig.security:type_name -> proxyswarm.SecurityMode
	3, // 1: proxyswarm.VlessConfig.tls:type_name -> proxyswarm.TLSConfig
	1, // 2: proxyswarm.VlessConfig.reality:type_name -> proxyswarm.VlessRealityConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_node_vless_proto_init() }
func file_node_vless_proto_init() {
	if File_node_vless_proto != nil {
		return
	}
	file_node_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_vless_proto_rawDesc), len(file_node_vless_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_vless_proto_goTypes,
		DependencyIndexes: file_node_vless_proto_depIdxs,
		EnumInfos:         file_node_vless_proto_enumTypes,
		MessageInfos:      file_node_vless_proto_msgTypes,
	}.Build()
	File_node_vless_proto = out.File
	file_node_vless_proto_goTypes = nil
	file_node_vless_proto_depIdxs = nil
}
