// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Account {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Used as UUID for VLESS/etc
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    /// Unix timestamp
    #[prost(int64, tag = "4")]
    pub expiry_time: i64,
    #[prost(string, repeated, tag = "5")]
    pub allowed_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HardwareStats {
    #[prost(double, tag = "1")]
    pub cpu_usage: f64,
    #[prost(uint64, tag = "2")]
    pub ram_used: u64,
    #[prost(uint64, tag = "3")]
    pub ram_total: u64,
    #[prost(uint64, tag = "4")]
    pub uptime: u64,
    #[prost(uint32, tag = "5")]
    pub cpu_cores: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TrafficStats {
    #[prost(uint64, tag = "1")]
    pub rx: u64,
    #[prost(uint64, tag = "2")]
    pub tx: u64,
    #[prost(double, tag = "3")]
    pub rx_rate: f64,
    #[prost(double, tag = "4")]
    pub tx_rate: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionStats {
    #[prost(uint32, tag = "1")]
    pub tcp: u32,
    #[prost(uint32, tag = "2")]
    pub udp: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserSessionStatus {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_agent: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InboundStatus {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub traffic: ::core::option::Option<TrafficStats>,
    #[prost(message, optional, tag = "3")]
    pub connections: ::core::option::Option<ConnectionStats>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountStatus {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub traffic: ::core::option::Option<TrafficStats>,
    #[prost(uint32, tag = "3")]
    pub online: u32,
    #[prost(message, repeated, tag = "4")]
    pub sessions: ::prost::alloc::vec::Vec<UserSessionStatus>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutboundStatus {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub traffic: ::core::option::Option<TrafficStats>,
    #[prost(bool, tag = "4")]
    pub excluded_from_totals: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HourlyMetrics {
    #[prost(int64, tag = "1")]
    pub hour_start_unix: i64,
    #[prost(double, tag = "2")]
    pub max_speed: f64,
    #[prost(uint64, tag = "3")]
    pub traffic_rx: u64,
    #[prost(uint64, tag = "4")]
    pub traffic_tx: u64,
    #[prost(uint32, tag = "5")]
    pub users: u32,
    #[prost(uint32, tag = "6")]
    pub inbounds: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeStatus {
    #[prost(message, optional, tag = "1")]
    pub hardware: ::core::option::Option<HardwareStats>,
    #[prost(message, repeated, tag = "2")]
    pub inbounds: ::prost::alloc::vec::Vec<InboundStatus>,
    #[prost(message, repeated, tag = "3")]
    pub accounts: ::prost::alloc::vec::Vec<AccountStatus>,
    #[prost(message, repeated, tag = "4")]
    pub outbounds: ::prost::alloc::vec::Vec<OutboundStatus>,
    #[prost(message, optional, tag = "5")]
    pub total_inbound_traffic: ::core::option::Option<TrafficStats>,
    #[prost(message, optional, tag = "6")]
    pub total_outbound_traffic: ::core::option::Option<TrafficStats>,
    #[prost(message, optional, tag = "7")]
    pub connections: ::core::option::Option<ConnectionStats>,
    #[prost(uint32, tag = "8")]
    pub sample_window_seconds: u32,
    #[prost(message, repeated, tag = "9")]
    pub hourly_metrics: ::prost::alloc::vec::Vec<HourlyMetrics>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcmeCertificateConfig {
    #[prost(string, tag = "1")]
    pub acme_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub acme_ca: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub acme_email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acme_domain: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub acme_port: i32,
    #[prost(int32, tag = "6")]
    pub acme_http_port: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomCertificateConfig {
    #[prost(string, tag = "1")]
    pub certificate_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key_pem: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CertificateConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(oneof = "certificate_config::Kind", tags = "2, 3")]
    pub kind: ::core::option::Option<certificate_config::Kind>,
}
/// Nested message and enum types in `CertificateConfig`.
pub mod certificate_config {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "2")]
        Acme(super::AcmeCertificateConfig),
        #[prost(message, tag = "3")]
        Custom(super::CustomCertificateConfig),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TlsConfig {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(string, tag = "2")]
    pub server_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub certificate_name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlessRealityConfig {
    #[prost(string, tag = "1")]
    pub dest: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub private_key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub short_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub sni: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub utls: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub spider_x: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlessConfig {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub flow: ::prost::alloc::string::String,
    #[prost(enumeration = "SecurityMode", tag = "3")]
    pub security: i32,
    #[prost(string, tag = "4")]
    pub transmission: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(message, optional, tag = "6")]
    pub reality: ::core::option::Option<VlessRealityConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecurityMode {
    None = 0,
    Tls = 1,
    Reality = 2,
}
impl SecurityMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::Tls => "TLS",
            Self::Reality => "REALITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "TLS" => Some(Self::Tls),
            "REALITY" => Some(Self::Reality),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hysteria2Config {
    #[prost(string, tag = "1")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub obfs_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub obfs_password: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub up_mbps: u32,
    #[prost(uint32, tag = "5")]
    pub down_mbps: u32,
    #[prost(message, optional, tag = "6")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(bool, tag = "7")]
    pub ignore_client_bandwidth: bool,
    #[prost(string, tag = "8")]
    pub masquerade: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub bbr_profile: ::prost::alloc::string::String,
    #[prost(bool, tag = "10")]
    pub brutal_debug: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrustTunnelConfig {
    #[prost(uint32, tag = "1")]
    pub http1_upload_buffer_size: u32,
    #[prost(uint32, tag = "2")]
    pub http2_initial_connection_window_size: u32,
    #[prost(uint32, tag = "3")]
    pub http2_initial_stream_window_size: u32,
    #[prost(uint32, tag = "4")]
    pub http2_max_concurrent_streams: u32,
    #[prost(uint32, tag = "5")]
    pub http2_max_frame_size: u32,
    #[prost(uint32, tag = "6")]
    pub http2_header_table_size: u32,
    #[prost(message, optional, tag = "7")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(string, tag = "8")]
    pub endpoint_hostname: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "9")]
    pub endpoint_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "10")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub certificate_pem: ::prost::alloc::string::String,
    #[prost(bool, tag = "13")]
    pub skip_verification: bool,
    #[prost(string, tag = "14")]
    pub upstream_protocol: ::prost::alloc::string::String,
    #[prost(bool, tag = "15")]
    pub anti_dpi: bool,
    #[prost(string, tag = "16")]
    pub custom_sni: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NaiveProxyConfig {
    /// "tcp", "udp", or empty for both
    #[prost(string, tag = "1")]
    pub network: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub quic_congestion_control: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub tls: ::core::option::Option<TlsConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WireGuardConfig {
    #[prost(string, tag = "1")]
    pub private_key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub peers: ::prost::alloc::vec::Vec<WireGuardPeer>,
    #[prost(int32, tag = "4")]
    pub mtu: i32,
    #[prost(int32, tag = "5")]
    pub workers: i32,
    /// 3 bytes
    #[prost(uint32, repeated, tag = "6")]
    pub reserved: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, tag = "7")]
    pub domain_strategy: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WireGuardPeer {
    #[prost(string, tag = "1")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub allowed_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag = "4")]
    pub reserved: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "5")]
    pub keepalive: u32,
    #[prost(string, tag = "6")]
    pub pre_shared_key: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Socks5InboundConfig {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub udp_enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Socks5OutboundConfig {
    #[prost(string, tag = "1")]
    pub server: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShadowsocksInboundConfig {
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub udp_enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShadowsocksOutboundConfig {
    #[prost(string, tag = "1")]
    pub server: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub plugin: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub plugin_opts: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub prefix: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub udp_enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlessReverseProxyConfig {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub portal_inbound_tag: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub portal_user_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelConfig {
    #[prost(string, tag = "1")]
    pub allowed_network: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TProxyConfig {
    /// tcp, udp, or tcp,udp
    #[prost(string, tag = "1")]
    pub network: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub sniffing_enabled: bool,
    #[prost(string, repeated, tag = "3")]
    pub sniffing_dest_override: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub sniffing_route_only: bool,
    #[prost(int32, tag = "5")]
    pub socket_mark: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrojanInboundConfig {
    #[prost(string, tag = "1")]
    pub password: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(string, tag = "3")]
    pub fallback: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrojanOutboundConfig {
    #[prost(string, tag = "1")]
    pub server: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub tls_enabled: bool,
    #[prost(string, tag = "5")]
    pub sni: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FullConfig {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub inbounds: ::prost::alloc::vec::Vec<InboundConfig>,
    #[prost(message, repeated, tag = "3")]
    pub accounts: ::prost::alloc::vec::Vec<Account>,
    #[prost(message, repeated, tag = "4")]
    pub outbounds: ::prost::alloc::vec::Vec<OutboundConfig>,
    #[prost(message, repeated, tag = "5")]
    pub routing_rules: ::prost::alloc::vec::Vec<RoutingRule>,
    #[prost(message, repeated, tag = "6")]
    pub certificates: ::prost::alloc::vec::Vec<CertificateConfig>,
    #[prost(message, optional, tag = "7")]
    pub dns: ::core::option::Option<DnsConfig>,
    #[prost(string, tag = "8")]
    pub link_remark_template: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InboundConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// e.g., "0.0.0.0"
    #[prost(string, tag = "2")]
    pub listen: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub port: i32,
    #[prost(enumeration = "CoreType", tag = "5")]
    pub core: i32,
    #[prost(message, repeated, tag = "4")]
    pub accounts: ::prost::alloc::vec::Vec<Account>,
    #[prost(bool, tag = "12")]
    pub enabled: bool,
    #[prost(
        oneof = "inbound_config::Protocol",
        tags = "6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17"
    )]
    pub protocol: ::core::option::Option<inbound_config::Protocol>,
}
/// Nested message and enum types in `InboundConfig`.
pub mod inbound_config {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Protocol {
        #[prost(message, tag = "6")]
        Vless(super::VlessConfig),
        #[prost(message, tag = "7")]
        Hysteria2(super::Hysteria2Config),
        #[prost(message, tag = "8")]
        Trusttunnel(super::TrustTunnelConfig),
        #[prost(message, tag = "9")]
        Naiveproxy(super::NaiveProxyConfig),
        #[prost(message, tag = "10")]
        Wireguard(super::WireGuardConfig),
        #[prost(message, tag = "11")]
        Socks5(super::Socks5InboundConfig),
        #[prost(message, tag = "13")]
        Shadowsocks(super::ShadowsocksInboundConfig),
        #[prost(message, tag = "14")]
        VlessReverseProxy(super::VlessReverseProxyConfig),
        #[prost(message, tag = "15")]
        Tproxy(super::TProxyConfig),
        #[prost(message, tag = "16")]
        Trojan(super::TrojanInboundConfig),
        #[prost(message, tag = "17")]
        Tunnel(super::TunnelConfig),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutboundConfig {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(enumeration = "OutboundType", tag = "2")]
    pub r#type: i32,
    #[prost(oneof = "outbound_config::Settings", tags = "3, 4, 5, 6, 7, 8, 9")]
    pub settings: ::core::option::Option<outbound_config::Settings>,
}
/// Nested message and enum types in `OutboundConfig`.
pub mod outbound_config {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Settings {
        #[prost(message, tag = "3")]
        Vless(super::VlessOutboundConfig),
        #[prost(message, tag = "4")]
        Trusttunnel(super::TrustTunnelConfig),
        #[prost(message, tag = "5")]
        Wireguard(super::WireGuardConfig),
        #[prost(message, tag = "6")]
        Socks5(super::Socks5OutboundConfig),
        #[prost(message, tag = "7")]
        Shadowsocks(super::ShadowsocksOutboundConfig),
        #[prost(message, tag = "8")]
        Trojan(super::TrojanOutboundConfig),
        #[prost(message, tag = "9")]
        Custom(super::CustomOutboundConfig),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomOutboundConfig {
    #[prost(string, tag = "1")]
    pub handler_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub config_json: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlessOutboundConfig {
    #[prost(string, tag = "1")]
    pub server: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    #[prost(string, tag = "3")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub flow: ::prost::alloc::string::String,
    #[prost(enumeration = "SecurityMode", tag = "5")]
    pub security: i32,
    #[prost(string, tag = "6")]
    pub transmission: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(message, optional, tag = "8")]
    pub reality: ::core::option::Option<VlessRealityConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutingRule {
    #[prost(string, repeated, tag = "1")]
    pub domain: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub ip: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub port: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub transport: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub protocol: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub outbound_tag: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub inbound_tag: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "8")]
    pub user: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsConfig {
    #[prost(message, repeated, tag = "1")]
    pub servers: ::prost::alloc::vec::Vec<DnsServerConfig>,
    #[prost(message, repeated, tag = "2")]
    pub hosts: ::prost::alloc::vec::Vec<DnsHostMapping>,
    #[prost(string, tag = "3")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tag: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub query_strategy: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub disable_cache: bool,
    #[prost(bool, tag = "7")]
    pub serve_stale: bool,
    #[prost(uint32, tag = "8")]
    pub serve_expired_ttl: u32,
    #[prost(bool, tag = "9")]
    pub disable_fallback: bool,
    #[prost(bool, tag = "10")]
    pub disable_fallback_if_match: bool,
    #[prost(bool, tag = "11")]
    pub enable_parallel_query: bool,
    #[prost(bool, tag = "12")]
    pub use_system_hosts: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DnsServerConfig {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
    #[prost(bool, tag = "4")]
    pub skip_fallback: bool,
    #[prost(string, repeated, tag = "5")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub expect_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub query_strategy: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tag: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub timeout_ms: u64,
    #[prost(bool, optional, tag = "10")]
    pub disable_cache: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "11")]
    pub serve_stale: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "12")]
    pub serve_expired_ttl: ::core::option::Option<u32>,
    #[prost(bool, tag = "13")]
    pub final_query: bool,
    #[prost(string, repeated, tag = "14")]
    pub unexpected_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DnsHostMapping {
    #[prost(string, tag = "1")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusRequest {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub hourly_metrics_hours: u32,
    #[prost(int64, tag = "3")]
    pub hourly_metrics_from_unix: i64,
    #[prost(int64, tag = "4")]
    pub hourly_metrics_to_unix: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcmeIssueRequest {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub challenge_type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub ca: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub port: i32,
    #[prost(string, tag = "7")]
    pub certificate_path: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub key_path: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcmeIssueResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub logs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "4")]
    pub expiry_time: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarpRegisterRequest {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarpRegistration {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub license: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub reserved: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "5")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub peer_public_key: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarpRegisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub registration: ::core::option::Option<WarpRegistration>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarpLicenseUpdateRequest {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub license: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarpLicenseUpdateResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub license: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CoreType {
    SingBox = 0,
    Xray = 1,
}
impl CoreType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SingBox => "SING_BOX",
            Self::Xray => "XRAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SING_BOX" => Some(Self::SingBox),
            "XRAY" => Some(Self::Xray),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OutboundType {
    Direct = 0,
    Block = 1,
    Vless = 2,
    Trusttunnel = 3,
    Wireguard = 4,
    Socks5 = 5,
    Shadowsocks = 6,
    Trojan = 7,
    Custom = 8,
}
impl OutboundType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Direct => "DIRECT",
            Self::Block => "BLOCK",
            Self::Vless => "VLESS",
            Self::Trusttunnel => "TRUSTTUNNEL",
            Self::Wireguard => "WIREGUARD",
            Self::Socks5 => "SOCKS5",
            Self::Shadowsocks => "SHADOWSOCKS",
            Self::Trojan => "TROJAN",
            Self::Custom => "CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECT" => Some(Self::Direct),
            "BLOCK" => Some(Self::Block),
            "VLESS" => Some(Self::Vless),
            "TRUSTTUNNEL" => Some(Self::Trusttunnel),
            "WIREGUARD" => Some(Self::Wireguard),
            "SOCKS5" => Some(Self::Socks5),
            "SHADOWSOCKS" => Some(Self::Shadowsocks),
            "TROJAN" => Some(Self::Trojan),
            "CUSTOM" => Some(Self::Custom),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistryServiceConfig {
    #[prost(message, repeated, tag = "1")]
    pub accounts: ::prost::alloc::vec::Vec<Account>,
    #[prost(message, repeated, tag = "2")]
    pub template_links: ::prost::alloc::vec::Vec<RegistryTemplateLink>,
    #[prost(string, tag = "3")]
    pub brand: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryTemplateLink {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub inbound_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub inbound_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub template: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistryUpdateConfigRequest {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<RegistryServiceConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistryUpdateConfigResponse {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<RegistryServiceConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryStatusRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryStatusResponse {
    #[prost(bool, tag = "1")]
    pub configured: bool,
    #[prost(uint32, tag = "2")]
    pub accounts: u32,
    #[prost(uint32, tag = "3")]
    pub template_links: u32,
    #[prost(int64, tag = "4")]
    pub updated_at_unix: i64,
}
