// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: registry/registry.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryManagementService_UpdateConfig_FullMethodName = "/proxyswarm.RegistryManagementService/UpdateConfig"
	RegistryManagementService_Status_FullMethodName       = "/proxyswarm.RegistryManagementService/Status"
)

// RegistryManagementServiceClient is the client API for RegistryManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryManagementServiceClient interface {
	UpdateConfig(ctx context.Context, in *RegistryUpdateConfigRequest, opts ...grpc.CallOption) (*RegistryUpdateConfigResponse, error)
	Status(ctx context.Context, in *RegistryStatusRequest, opts ...grpc.CallOption) (*RegistryStatusResponse, error)
}

type registryManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryManagementServiceClient(cc grpc.ClientConnInterface) RegistryManagementServiceClient {
	return &registryManagementServiceClient{cc}
}

func (c *registryManagementServiceClient) UpdateConfig(ctx context.Context, in *RegistryUpdateConfigRequest, opts ...grpc.CallOption) (*RegistryUpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateConfigResponse)
	err := c.cc.Invoke(ctx, RegistryManagementService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryManagementServiceClient) Status(ctx context.Context, in *RegistryStatusRequest, opts ...grpc.CallOption) (*RegistryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryStatusResponse)
	err := c.cc.Invoke(ctx, RegistryManagementService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryManagementServiceServer is the server API for RegistryManagementService service.
// All implementations must embed UnimplementedRegistryManagementServiceServer
// for forward compatibility.
type RegistryManagementServiceServer interface {
	UpdateConfig(context.Context, *RegistryUpdateConfigRequest) (*RegistryUpdateConfigResponse, error)
	Status(context.Context, *RegistryStatusRequest) (*RegistryStatusResponse, error)
	mustEmbedUnimplementedRegistryManagementServiceServer()
}

// UnimplementedRegistryManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryManagementServiceServer struct{}

func (UnimplementedRegistryManagementServiceServer) UpdateConfig(context.Context, *RegistryUpdateConfigRequest) (*RegistryUpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedRegistryManagementServiceServer) Status(context.Context, *RegistryStatusRequest) (*RegistryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRegistryManagementServiceServer) mustEmbedUnimplementedRegistryManagementServiceServer() {
}
func (UnimplementedRegistryManagementServiceServer) testEmbeddedByValue() {}

// UnsafeRegistryManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryManagementServiceServer will
// result in compilation errors.
type UnsafeRegistryManagementServiceServer interface {
	mustEmbedUnimplementedRegistryManagementServiceServer()
}

func RegisterRegistryManagementServiceServer(s grpc.ServiceRegistrar, srv RegistryManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryManagementService_ServiceDesc, srv)
}

func _RegistryManagementService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryUpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryManagementServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryManagementService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryManagementServiceServer).UpdateConfig(ctx, req.(*RegistryUpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryManagementService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryManagementServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryManagementService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryManagementServiceServer).Status(ctx, req.(*RegistryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryManagementService_ServiceDesc is the grpc.ServiceDesc for RegistryManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxyswarm.RegistryManagementService",
	HandlerType: (*RegistryManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConfig",
			Handler:    _RegistryManagementService_UpdateConfig_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RegistryManagementService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry/registry.proto",
}
